/* Formatted on 2009/11/09 01:11 (Formatter Plus v4.8.5) */
DROP TABLE application CASCADE CONSTRAINTS;
DROP TABLE inner_application CASCADE CONSTRAINTS;
DROP TABLE outer_application CASCADE CONSTRAINTS;
DROP TABLE individual_application CASCADE CONSTRAINTS;
DROP TABLE free_application CASCADE CONSTRAINTS;
DROP TABLE optional_application CASCADE CONSTRAINTS;

DROP TABLE employee CASCADE CONSTRAINTS;
DROP TABLE programmer CASCADE CONSTRAINTS;
DROP TABLE tester CASCADE CONSTRAINTS;
DROP TABLE maintancer CASCADE CONSTRAINTS;
DROP TABLE tech_writer CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;
DROP TABLE installed;
DROP TABLE development;

DROP TABLE LANGUAGE CASCADE CONSTRAINTS;
DROP TABLE write_lang;

DROP TABLE prog_language CASCADE CONSTRAINTS;
DROP TABLE devel_lang;

DROP SEQUENCE applic_id;
DROP SEQUENCE employee_id;
DROP SEQUENCE customer_id;
DROP SEQUENCE la;
DROP SEQUENCE pr_la;

DROP PACKAGE data_manager;


COMMIT ;