/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on 02.05.2010, 17:39:21
 */
package karymov;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FileDialog;
import java.awt.Font;
import java.awt.TextArea;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.Reader;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Антон
 */
public class MainForm extends javax.swing.JFrame implements IMainForm {

    Controller controller = null;
    String currentFileName = "";
    String textOpenedProgramm;
    byte buf[];
    int height;
    int width;
    int coordinateX;
    int coordinateY;
    // String fileName;
    LinkedList<String> list;

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        controller = new Controller(this);
        height = Memento.getMemento().getHeight();
        width = Memento.getMemento().getWidth();
        coordinateX = Memento.getMemento().getCoordinateX();
        coordinateY = Memento.getMemento().getCoordinateY();
        list = Memento.getMemento().getList();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameAbout = new javax.swing.JFrame();
        FirstDeveloper = new javax.swing.JLabel();
        SecondDeveloper = new javax.swing.JLabel();
        ThirdDeveloper = new javax.swing.JLabel();
        CloseAboutButton = new javax.swing.JButton();
        SaveFrame = new javax.swing.JFrame();
        SaveFileChooser = new javax.swing.JFileChooser();
        OpenFrame = new javax.swing.JFrame();
        OpenFileChooser = new javax.swing.JFileChooser();
        FileChangedWarningFrame = new javax.swing.JFrame();
        SaveWarningButton = new javax.swing.JButton();
        NotSaveButtonWarning = new javax.swing.JButton();
        CanselButtonWarning = new javax.swing.JButton();
        FileChangedLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        RunButton = new javax.swing.JButton();
        DebugButton = new javax.swing.JButton();
        StepNextButton = new javax.swing.JButton();
        StepOverButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPanel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsolePanel = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMenuItem = new javax.swing.JMenuItem();
        SaveMenuItem = new javax.swing.JMenuItem();
        SaveAsMenuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();
        RecentFileMenu = new javax.swing.JMenu();
        HelpMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        FrameAbout.setTitle("About");
        FrameAbout.setMinimumSize(new java.awt.Dimension(400, 300));

        FirstDeveloper.setText("FirstDeveloper");

        SecondDeveloper.setText("SecondDeveloper");

        ThirdDeveloper.setText("ThirdDeveloper");

        CloseAboutButton.setText("Close");
        CloseAboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseAboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameAboutLayout = new javax.swing.GroupLayout(FrameAbout.getContentPane());
        FrameAbout.getContentPane().setLayout(FrameAboutLayout);
        FrameAboutLayout.setHorizontalGroup(
            FrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecondDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ThirdDeveloper, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
            .addGroup(FrameAboutLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(CloseAboutButton)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        FrameAboutLayout.setVerticalGroup(
            FrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameAboutLayout.createSequentialGroup()
                .addGroup(FrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SecondDeveloper, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(ThirdDeveloper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(FirstDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(CloseAboutButton)
                .addGap(41, 41, 41))
        );

        SaveFrame.setMinimumSize(new java.awt.Dimension(600, 400));

        SaveFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        SaveFileChooser.setFileFilter(null);

        javax.swing.GroupLayout SaveFrameLayout = new javax.swing.GroupLayout(SaveFrame.getContentPane());
        SaveFrame.getContentPane().setLayout(SaveFrameLayout);
        SaveFrameLayout.setHorizontalGroup(
            SaveFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(SaveFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SaveFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SaveFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        SaveFrameLayout.setVerticalGroup(
            SaveFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(SaveFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(SaveFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(SaveFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        OpenFrame.setMinimumSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout OpenFrameLayout = new javax.swing.GroupLayout(OpenFrame.getContentPane());
        OpenFrame.getContentPane().setLayout(OpenFrameLayout);
        OpenFrameLayout.setHorizontalGroup(
            OpenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 586, Short.MAX_VALUE)
            .addGroup(OpenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OpenFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(OpenFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        OpenFrameLayout.setVerticalGroup(
            OpenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 377, Short.MAX_VALUE)
            .addGroup(OpenFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(OpenFrameLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(OpenFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        FileChangedWarningFrame.setTitle("Warning!!!");
        FileChangedWarningFrame.setMinimumSize(new java.awt.Dimension(450, 200));

        SaveWarningButton.setText("Сохранить");
        SaveWarningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveWarningButtonActionPerformed(evt);
            }
        });

        NotSaveButtonWarning.setText("Не сохранять");
        NotSaveButtonWarning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NotSaveButtonWarningActionPerformed(evt);
            }
        });

        CanselButtonWarning.setText("Отмена");
        CanselButtonWarning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanselButtonWarningActionPerformed(evt);
            }
        });

        FileChangedLabel.setText("FileChangedLabel");

        javax.swing.GroupLayout FileChangedWarningFrameLayout = new javax.swing.GroupLayout(FileChangedWarningFrame.getContentPane());
        FileChangedWarningFrame.getContentPane().setLayout(FileChangedWarningFrameLayout);
        FileChangedWarningFrameLayout.setHorizontalGroup(
            FileChangedWarningFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FileChangedWarningFrameLayout.createSequentialGroup()
                .addGroup(FileChangedWarningFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FileChangedWarningFrameLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(FileChangedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                    .addGroup(FileChangedWarningFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(SaveWarningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NotSaveButtonWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(CanselButtonWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
        );
        FileChangedWarningFrameLayout.setVerticalGroup(
            FileChangedWarningFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FileChangedWarningFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileChangedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(FileChangedWarningFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveWarningButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NotSaveButtonWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CanselButtonWarning, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Compiler");
        setMinimumSize(new java.awt.Dimension(565, 389));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        RunButton.setText("Run");
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        DebugButton.setText("Debug");
        DebugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebugButtonActionPerformed(evt);
            }
        });

        StepNextButton.setText("StepNext");
        StepNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepNextButtonActionPerformed(evt);
            }
        });

        StepOverButton.setText("StepOver");
        StepOverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepOverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveButton)
                .addGap(18, 18, 18)
                .addComponent(RunButton)
                .addGap(55, 55, 55)
                .addComponent(DebugButton)
                .addGap(18, 18, 18)
                .addComponent(StepNextButton)
                .addGap(18, 18, 18)
                .addComponent(StepOverButton)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(RunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StepNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DebugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StepOverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TextPanel.setColumns(20);
        TextPanel.setRows(5);
        jScrollPane1.setViewportView(TextPanel);

        ConsolePanel.setColumns(20);
        ConsolePanel.setRows(5);
        jScrollPane2.setViewportView(ConsolePanel);

        jMenuBar1.setName(""); // NOI18N

        FileMenu.setText("File");

        OpenMenuItem.setText("Open");
        OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(OpenMenuItem);

        SaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveMenuItem.setText("Save");
        SaveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(SaveMenuItem);

        SaveAsMenuItem.setText("Save As...");
        SaveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(SaveAsMenuItem);

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItem(evt);
            }
        });
        FileMenu.add(ExitMenuItem);

        RecentFileMenu.setText("Open Recent File");
        FileMenu.add(RecentFileMenu);

        jMenuBar1.add(FileMenu);

        HelpMenu.setText("Help");

        jMenuItem6.setText("About");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        HelpMenu.add(jMenuItem6);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuItemActionPerformed
        OpenFrame.setTitle("Open File");
        setCenterPosition(OpenFrame);
        javax.swing.filechooser.FileFilter fileFilter = new MyFilter(".txt");
        OpenFileChooser.addChoosableFileFilter(fileFilter);
        if (OpenFileChooser.showOpenDialog(null) != OpenFileChooser.APPROVE_OPTION) {
            return;//Нажали Cancel
        }
        ;
        File file = OpenFileChooser.getSelectedFile();
        if (file != null) {
            currentFileName = OpenFileChooser.getSelectedFile().getPath();
            controller.openFile(file);
            if (weNeedAddRecentFile(list, currentFileName)) {
                additionRecentFile(list, currentFileName);
                createRecentFile(file);
            }
            textOpenedProgramm = TextPanel.getText();
        }
    }//GEN-LAST:event_OpenMenuItemActionPerformed
    private void createRecentFile(File file) {
        final JMenuItem newItem = new JMenuItem(file.getName());
        newItem.setToolTipText(file.getPath());
        newItem.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                recentFilesItemClick(newItem.getToolTipText());
            }

            private void recentFilesItemClick(String toolTipText) {
                File file = new File(toolTipText);
                controller.openFile(file);
                currentFileName = toolTipText;
            }
        });
        RecentFileMenu.add(newItem);
    }
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        try {
            if (currentFileName.equals("")) {
                SaveAsMenuItemActionPerformed(null);
            } else {
                controller.saveFile(TextPanel.getText(), currentFileName);
                textOpenedProgramm = TextPanel.getText();
                ConsolePanel.setText("File saved in " + currentFileName);
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_SaveButtonActionPerformed
    }
        private void ExitMenuItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItem
            String textCurrentProgramm = TextPanel.getText();
            if (textCurrentProgramm.equals(textOpenedProgramm) || textCurrentProgramm.equals("")) {
//                int beforeEscapeHight = MainForm.this.getHeight();
//                int beforeEscapeWidth = MainForm.this.getWidth();
//                int beforeEscapeCoordinateX = MainForm.this.getX();
//                int beforeEscapeCoordinateY = MainForm.this.getY();
//                LinkedList<String> blist = this.list;
                Memento.getMemento().saveBounds(MainForm.this.getHeight(),
                        MainForm.this.getWidth(), MainForm.this.getX(), MainForm.this.getY(), this.list);
                System.exit(0);
            } else {
                FileChangedLabel.setText("Сохранить изменения в файле: " + currentFileName + "???");
                setCenterPosition(FileChangedWarningFrame);
                FileChangedWarningFrame.setVisible(true);
            }

        }//GEN-LAST:event_ExitMenuItem

        private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed
            printInConsole(controller.runProgram(TextPanel.getText()));
            //controller.runProgramm(TextPanel.getText());
        }//GEN-LAST:event_RunButtonActionPerformed

        private void CloseAboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseAboutButtonActionPerformed
            FrameAbout.hide();
        }//GEN-LAST:event_CloseAboutButtonActionPerformed

        private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
            setCenterPosition(FrameAbout);
            FrameAbout.show();
            FirstDeveloper.setVisible(true);
            SecondDeveloper.setVisible(true);
            ThirdDeveloper.setVisible(true);
            CloseAboutButton.setVisible(true);
        }//GEN-LAST:event_AboutActionPerformed

        private void DebugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebugButtonActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_DebugButtonActionPerformed

        private void StepNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepNextButtonActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_StepNextButtonActionPerformed

        private void StepOverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepOverButtonActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_StepOverButtonActionPerformed

        private void SaveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuItemActionPerformed
            SaveButtonActionPerformed(null);
        }//GEN-LAST:event_SaveMenuItemActionPerformed

        private void SaveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsMenuItemActionPerformed
            SaveFrame.setTitle("Save As...");
            setCenterPosition(SaveFrame);
            javax.swing.filechooser.FileFilter filter = new MyFilter(".txt");
            SaveFileChooser.addChoosableFileFilter(filter);
            if (SaveFileChooser.showSaveDialog(null) != SaveFileChooser.APPROVE_OPTION) {
                return;//Нажали Cancel
            }
            ;
            currentFileName = SaveFileChooser.getSelectedFile().getPath() + ".txt";
            SaveButtonActionPerformed(null);
        }//GEN-LAST:event_SaveAsMenuItemActionPerformed

        private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
            ExitMenuItem(null);
        }//GEN-LAST:event_formWindowClosing

        private void CanselButtonWarningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanselButtonWarningActionPerformed
            FileChangedWarningFrame.hide();
        }//GEN-LAST:event_CanselButtonWarningActionPerformed

        private void NotSaveButtonWarningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NotSaveButtonWarningActionPerformed
            System.exit(0);
        }//GEN-LAST:event_NotSaveButtonWarningActionPerformed

        private void SaveWarningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveWarningButtonActionPerformed
            SaveButtonActionPerformed(null);
            FileChangedWarningFrame.hide();
        }//GEN-LAST:event_SaveWarningButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception exception) {
                }
                Memento.getMemento().loadBounds();
                MainForm mainForm = new MainForm();
                loadReacentFile(mainForm);
                mainForm.TextPanel.setFont(new Font("Times New Roman", Font.BOLD, 14));
                mainForm.ConsolePanel.setFont(new Font("Times New Roman", Font.BOLD, 14));
                mainForm.setBounds(mainForm.coordinateX, mainForm.coordinateY, mainForm.width, mainForm.height);
                mainForm.setVisible(true);
            }

            private void loadReacentFile(MainForm mainForm) {
                for (String rfile : mainForm.list) {

                    File file = new File(rfile);
                    mainForm.createRecentFile(file);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CanselButtonWarning;
    private javax.swing.JButton CloseAboutButton;
    private javax.swing.JTextArea ConsolePanel;
    private javax.swing.JButton DebugButton;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JLabel FileChangedLabel;
    private javax.swing.JFrame FileChangedWarningFrame;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel FirstDeveloper;
    private javax.swing.JFrame FrameAbout;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JButton NotSaveButtonWarning;
    private javax.swing.JFileChooser OpenFileChooser;
    private javax.swing.JFrame OpenFrame;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JMenu RecentFileMenu;
    private javax.swing.JButton RunButton;
    private javax.swing.JMenuItem SaveAsMenuItem;
    private javax.swing.JButton SaveButton;
    private javax.swing.JFileChooser SaveFileChooser;
    private javax.swing.JFrame SaveFrame;
    private javax.swing.JMenuItem SaveMenuItem;
    private javax.swing.JButton SaveWarningButton;
    private javax.swing.JLabel SecondDeveloper;
    private javax.swing.JButton StepNextButton;
    private javax.swing.JButton StepOverButton;
    private javax.swing.JTextArea TextPanel;
    private javax.swing.JLabel ThirdDeveloper;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void setTextInTextPanel(String text) {
        TextPanel.setText(text);
    }

    public String getTextInTextPanel() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setTextInConsolePanel(String text) {
        ConsolePanel.setText(text);
    }

    public void clearTextPanel() {
        TextPanel.setText(null);
    }

    public void clearConsolePanel() {
        ConsolePanel.setText(null);
    }

    public void printInConsole(String text) {
        ConsolePanel.setText(text);
    }

    public JTextArea getTextPanel() {
        return TextPanel;
    }

    public boolean weNeedAddRecentFile(LinkedList<String> list, String addingRecentFile) {
        for (String havingRecentFile : list) {
            if (havingRecentFile.equals(addingRecentFile)) {
                return false;
            }
        }
        return true;
    }

    public void additionRecentFile(LinkedList<String> list, String addingRecentFile) {
        for (String havingRecentFile : list) {
            if (havingRecentFile.equals(addingRecentFile)) {
                list.remove(havingRecentFile);
            }
        }
        list.add(addingRecentFile);

    }

    private static void setCenterPosition(JFrame frame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = frame.getPreferredSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        frame.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
    }
}
