/*
 * MainWindow.java
 *
 * Created on 11.04.2010, 15:55:40
 */
package savenko;

import savenko.ast.Program;
import savenko.ast.Position;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;

public class MainWindow extends javax.swing.JFrame implements IMainView {

     Program programm = null;
     Controler controler = null;

     /** Creates new form MainWindow */
     public MainWindow() {
          initComponents();
          controler = new Controler(this);
     }

     /** This method is called from within the constructor to
      * initialize the form.
      * WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jScrollPane1 = new javax.swing.JScrollPane();
          programmTextField = new javax.swing.JTextPane();
          jPanel1 = new javax.swing.JPanel();
          openFileButton = new javax.swing.JButton();
          executeButton = new javax.swing.JButton();
          exitButton = new javax.swing.JButton();
          undoButton = new javax.swing.JButton();
          redoButton = new javax.swing.JButton();
          debugButton = new javax.swing.JButton();
          jScrollPane2 = new javax.swing.JScrollPane();
          consoleTextField = new javax.swing.JTextArea();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

          programmTextField.setName("programmTextField"); // NOI18N
          jScrollPane1.setViewportView(programmTextField);
          programmTextField.getAccessibleContext().setAccessibleName("ProgrammTextField");

          openFileButton.setText("Open File");
          openFileButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    openFileButtonActionPerformed(evt);
               }
          });

          executeButton.setText("|>");
          executeButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    executeButtonClick(evt);
               }
          });

          exitButton.setText("Exit");
          exitButton.setName("Exit"); // NOI18N
          exitButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ExitButtonClick(evt);
               }
          });

          undoButton.setText("<=");

          redoButton.setText("=>");

          debugButton.setText("|_| |>");
          debugButton.setMaximumSize(new java.awt.Dimension(45, 23));
          debugButton.setMinimumSize(new java.awt.Dimension(45, 23));
          debugButton.setPreferredSize(new java.awt.Dimension(45, 23));

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(openFileButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(executeButton)
                    .addGap(36, 36, 36)
                    .addComponent(debugButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(undoButton)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(redoButton)
                    .addGap(31, 31, 31)
                    .addComponent(exitButton)
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(redoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(undoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(debugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                         .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(executeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap())
          );

          exitButton.getAccessibleContext().setAccessibleName("ExitButton");

          consoleTextField.setColumns(20);
          consoleTextField.setRows(5);
          jScrollPane2.setViewportView(consoleTextField);
          consoleTextField.getAccessibleContext().setAccessibleName("consoleTextField");

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

    private void executeButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonClick
         controler.interpret();
    }//GEN-LAST:event_executeButtonClick

     private void debugButtonClick() {
          controler.debug();
     }

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
         //"W:/WorkspaceForJava/Interpriter/src/savenko/1.txt"
         programmTextField.setText(null);
         String filename = "src/savenko/1.txt";
         BufferedReader in = null;

         try {
              in = new BufferedReader(new InputStreamReader(new FileInputStream(filename)));
         } catch (FileNotFoundException e1) {
              e1.printStackTrace();
         }
         try {
              while (in.ready()) {
                   programmTextField.setText(programmTextField.getText() + in.readLine());
                   if (in.ready()) {
                        programmTextField.setText(programmTextField.getText() + "\n");
                   }
              }
         } catch (IOException e) {
              e.printStackTrace();
         } finally {
              //in.close();
         }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void ExitButtonClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonClick
         System.exit(0);
    }//GEN-LAST:event_ExitButtonClick

     public static void main(String args[]) {
          java.awt.EventQueue.invokeLater(new Runnable() {

               public void run() {
                    new MainWindow().setVisible(true);
               }
          });

     }

     @Override
     public String getProgramText() {
          return programmTextField.getText();
     }

     @Override
     public void printError(String error, Position position) {
          String str_position = "";
          if (position != null)
               str_position =
                  "( строка: " + position.getRowNum() +
                  " столбец: " + position.getColNumBeg() + " )";
          String full_error = "Error!: " + error + " " + str_position;

          if (error == null) {
               consoleTextField.setText(null);
          } else {
               if (consoleTextField.getText() == null)
                    consoleTextField.setText(full_error);
               else
                    consoleTextField.setText(consoleTextField.getText() + "\n" + full_error);
          }
     }

     @Override
     public void setProgramText(String program) {
          programmTextField.setText(program);
     }

     @Override
     public void printResult(String result) {
          if (result == null) {
               consoleTextField.setText("BuildSuccessfull!");
          } else {
               consoleTextField.setText("BuildSuccessfull!\n" + result);
          }
     }


     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JTextArea consoleTextField;
     private javax.swing.JButton debugButton;
     private javax.swing.JButton executeButton;
     private javax.swing.JButton exitButton;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane2;
     private javax.swing.JButton openFileButton;
     private javax.swing.JTextPane programmTextField;
     private javax.swing.JButton redoButton;
     private javax.swing.JButton undoButton;
     // End of variables declaration//GEN-END:variables
}
