/*
 * ChooserPanel.java
 *
 * Created on 22 Декабрь 2008 г., 20:58
 */

package eda.tm.gui;

/**
 *
 * @author  nastya
 */
public class ChooserPanel extends javax.swing.JPanel {

    /** Creates new form ChooserPanel */
    public ChooserPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rbShowTable = new javax.swing.JRadioButton();
        rbGenerateTex = new javax.swing.JRadioButton();
        rbShowTableGenerateTex = new javax.swing.JRadioButton();

        buttonGroup1.add(rbShowTable);
        rbShowTable.setSelected(true);
        rbShowTable.setText("Show Table only");

        buttonGroup1.add(rbGenerateTex);
        rbGenerateTex.setText("Generate tex only");

        buttonGroup1.add(rbShowTableGenerateTex);
        rbShowTableGenerateTex.setText("Show table and generate tex");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbShowTable)
                    .addComponent(rbGenerateTex)
                    .addComponent(rbShowTableGenerateTex))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(rbShowTable)
                .addGap(18, 18, 18)
                .addComponent(rbGenerateTex)
                .addGap(18, 18, 18)
                .addComponent(rbShowTableGenerateTex)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JRadioButton rbGenerateTex;
    public javax.swing.JRadioButton rbShowTable;
    public javax.swing.JRadioButton rbShowTableGenerateTex;
    // End of variables declaration//GEN-END:variables

}
