package archiver;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author HarpSerg
 */



public class GUI extends javax.swing.JFrame {

    /** Creates new form NewApplication */
    public GUI() {
        initComponents();
        buttonGroup1.add(hufChoosen);
        buttonGroup1.add(arithmChoosen);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        hufChoosen = new javax.swing.JRadioButton();
        arithmChoosen = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        input = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        browse = new javax.swing.JButton();
        output = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        generateName = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        log = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        execute = new javax.swing.JButton();
        cleareLog = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        jFileChooser1.setCurrentDirectory(new java.io.File("D:\\test"));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Archivator");
        setBounds(new java.awt.Rectangle(0, 0, 640, 480));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Method"));

        hufChoosen.setSelected(true);
        hufChoosen.setText("Huffman");

        arithmChoosen.setText("Arithmetic");
        arithmChoosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arithmChoosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arithmChoosen)
                    .addComponent(hufChoosen))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(hufChoosen)
                .addGap(3, 3, 3)
                .addComponent(arithmChoosen)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("File"));

        jLabel1.setText("input:");

        browse.setText("browse");
        browse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseActionPerformed(evt);
            }
        });

        jLabel2.setText("output:");

        generateName.setText("generate");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(output, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generateName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(browse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generateName))
                .addGap(29, 29, 29))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Log"));

        log.setColumns(20);
        log.setRows(5);
        jScrollPane1.setViewportView(log);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        execute.setText("execute");
        execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeActionPerformed(evt);
            }
        });

        cleareLog.setText("Cleare log");
        cleareLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleareLogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(execute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(cleareLog)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(execute)
                    .addComponent(cleareLog))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        fileMenu.setText("File");

        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 408, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(25, 25, 25)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeActionPerformed
        if (generateName.isSelected()) {
            output.setText("automatic");
            if (input.getText().length() >= 3) {
                if (getAttention()) {
                    if(JOptionPane.showConfirmDialog(null,getQuestion(), "attention",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                        execute(null);
                    }
                } else {
                    execute(null);
                }
            } else {
               JOptionPane.showMessageDialog(rootPane, "Error!!! incorrect input file name!!!");
            }
        } else {
            if (fileExist( output.getText() ) ) {
                if(JOptionPane.showConfirmDialog(null,"this operation will overwrite file "
                        + output.getText() + ". Proceed?", "attention",JOptionPane.YES_NO_OPTION,
                        JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
                    if (!input.getText().equals(output.getText())) {
                        execute(output.getText());
                    } else {                        
                        JOptionPane.showMessageDialog(rootPane, "You can't overwrite the input file:" + output.getText() + "!!!");
                    }
                }
            } else {
                if (input.getText().length() >= 3) {
                    execute(output.getText());
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Error!!! incorrect input file name!!!");
                }
            }
        }
}//GEN-LAST:event_executeActionPerformed

    private void browseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseActionPerformed
        jFileChooser1.setSelectedFile(new File(input.getText()));
        if (jFileChooser1.showOpenDialog(jLabel1) == JFileChooser.APPROVE_OPTION) {
            input.setText(jFileChooser1.getSelectedFile().getPath());
        }
}//GEN-LAST:event_browseActionPerformed

    private void arithmChoosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arithmChoosenActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_arithmChoosenActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        jFileChooser1.setSelectedFile(new File(input.getText()));
        jFileChooser1.showOpenDialog(jLabel1);
        input.setText(jFileChooser1.getSelectedFile().getPath());
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void cleareLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleareLogActionPerformed
        log.setText("");
}//GEN-LAST:event_cleareLogActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws IOException {
       
		String s = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        try {
            //s = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
            UIManager.setLookAndFeel(s);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });        
    }   

    private void executeCoding(String outfilename) {
        String inFileName = input.getText();
        try {            
            if(hufChoosen.isSelected()) {
                setLog("huffman coding started at " + getDate() + "\n");
                HuffCoder coder = new HuffCoder();
                coder.code(inFileName, outfilename);
                setLog("huffman coding finished at " + getDate() + "\n");
            } else {
                setLog("Arithmetic coding started at " + getDate() + "\n");
                ArithmCode_Decode input = new ArithmCode_Decode();
                input.CalcFrequency(inFileName);                
                input.CodeArith(inFileName, outfilename);
                //ArithmCode_Decode c = new ArithmCode_Decode();
                //c.CodeArith(inFileName, outfilename);
                setLog("Arithmetic coding finished at " + getDate() + "\n");
            }
            
        } catch (IOException ex) {            
            JOptionPane.showMessageDialog(rootPane, "Error!!! incorrect input or output file name!!!");
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void executeHufDecoding(String outfilename) {
        String inFileName = input.getText();
        try {
            setLog("huffman decoding started at " + getDate() + "\n");
            HuffDecoder decoder = new HuffDecoder();
            decoder.decode(inFileName, outfilename);
            setLog("huffman decoding finished at " + getDate() + "\n");    
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error!!! incorrect input or output file name!!!");
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void executeArfDecoding(String outfilename) {
        try {
            String inFileName = input.getText();
            setLog("Arithmetic coding started at " + getDate() + "\n");
            ArithmCode_Decode input = new ArithmCode_Decode();
            input.CalcFrequency(inFileName);
            input.DecodeArith(inFileName, outfilename);
            setLog("Arithmetic coding finished at " + getDate() + "\n");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
   

    private void execute(String newname) {
        String inFileName = input.getText();
        String nametouse = inFileName.substring(0, inFileName.length()-3);
        if(newname != null) {
            if (inFileName.substring(inFileName.length() - 3).equals("huf"))
                executeHufDecoding(newname);
            if (inFileName.substring(inFileName.length() - 3).equals("arf")) {
                executeArfDecoding(newname);
            }
            if (!inFileName.substring(inFileName.length() - 3).equals("huf") && !inFileName.substring(inFileName.length() - 3).equals("arf") )
                executeCoding(newname);
            
        } else {
            if (inFileName.substring(inFileName.length() - 3).equals("huf"))
                executeHufDecoding(nametouse + "dec");
            if (inFileName.substring(inFileName.length() - 3).equals("arf")) {
                executeArfDecoding(nametouse + "dec");
            }
            if (!inFileName.substring(inFileName.length() - 3).equals("huf") && !inFileName.substring(inFileName.length() - 3).equals("arf") ) {
                String type;
                if(hufChoosen.isSelected())
                    type = "huf";
                else
                    type = "arf";
                executeCoding(nametouse + type);
            }
        }
    }        

    private boolean getAttention() {
        String inFileName = input.getText();
        if ( inFileName.substring(inFileName.length() - 3).equals("huf") || inFileName.substring(inFileName.length() - 3).equals("arf") ) {
            File file = new File(inFileName.substring(0,inFileName.length() - 3) + "dec");
            if (file.exists())
                return true;            
        } else {
            String type;
            if(hufChoosen.isSelected())
                type = "huf";
            else
                type = "arf";
            File file = new File(inFileName.substring(0,inFileName.length() - 3) + type);
            if (file.exists())
                return true;            
        }
        return false;
    }
    
    private String getQuestion() {
        String inFileName = input.getText();
        if ( inFileName.substring(inFileName.length() - 3).equals("huf") || inFileName.substring(inFileName.length() - 3).equals("arf") ) {
            return "this operation will overwrite file " +
                inFileName.substring(0,inFileName.length() - 3) + "dec" + ". Proceed?";            
        } else {            
            String type;
            if(hufChoosen.isSelected())
                type = "huf";
            else
                type = "arf";
            return "this operation will overwrite file " +
                inFileName.substring(0,inFileName.length() - 3) + type + ". Proceed?";
        }
    }

    private String getDate() {
        Date now = new Date();
        return now.toString();
    }

    private void setLog(String message) {
        log.setText(log.getText() + message);
    }

    private boolean fileExist(String newname) {
    File file = new File(newname);
    if (file.exists())
    return true;
    return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton arithmChoosen;
    private javax.swing.JButton browse;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cleareLog;
    private javax.swing.JButton execute;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JRadioButton generateName;
    private javax.swing.JRadioButton hufChoosen;
    private javax.swing.JTextField input;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea log;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JTextField output;
    // End of variables declaration//GEN-END:variables

}
