DELETE FROM SESSION;
  
DELETE FROM GROUPS;
DELETE FROM SUBJECT;
DELETE FROM STUDENT_OCHNIK;
DELETE FROM STUDENT_DISTANT;
DELETE FROM STUDENT;
 
DELETE FROM TEACHER;
  
DELETE FROM STUDENT_EXAM;