INSERT INTO owners(title, age) VALUES ('Lapin Konstantine', 41)
INSERT INTO owners(title, age) VALUES ('Lapin Sergey', 70)
INSERT INTO owners(title, age) VALUES ('Евлампий Сидоров', 31)
INSERT INTO owners(title)      VALUES ('"OOO Колхоз"')
INSERT INTO owners(title, age) VALUES ('Иван Алексеев', 20)
INSERT INTO owners(title, age) VALUES ('Андрей Дубинин', 23)
INSERT INTO owners(title, age) VALUES ('Михаил Дробиченко', 25)
INSERT INTO owners(title)      VALUES ('"OOO Терком"')

INSERT INTO gas_stations(address) VALUES ('Будапештская')
INSERT INTO gas_stations(address) VALUES ('Гашека')
INSERT INTO gas_stations(address) VALUES ('пр. Луначарского')
INSERT INTO gas_stations(address) VALUES ('пр. Энгельса')
INSERT INTO gas_stations(address) VALUES ('ул. Ярослава Гашека')
INSERT INTO gas_stations(address) VALUES ('Клочков пер.')
INSERT INTO gas_stations(address) VALUES ('пр. Большевиков')
INSERT INTO gas_stations(address) VALUES ('ул. Колонтай')

INSERT INTO parking_places(title) VALUES ('Подречная')
INSERT INTO parking_places(title) VALUES ('Сеновал')
INSERT INTO parking_places(title) VALUES ('У Семёна')
INSERT INTO parking_places(title) VALUES ('рядом с домом')

INSERT INTO free(parking_id) VALUES (4)
INSERT INTO free(parking_id) VALUES (2)
INSERT INTO paying(tax_in_month, parking_id) VALUES ('50$', 1)
INSERT INTO paying(tax_in_month, parking_id) VALUES ('20$', 3)

INSERT INTO mark(title, country) VALUES ('mersedes', 'США')
INSERT INTO mark(title, country) VALUES ('Фиат', 'Россия')
INSERT INTO mark(title, country) VALUES ('mersedes', 'Россия')
INSERT INTO mark(title, country) VALUES ('ВАЗ', 'Russia')
INSERT INTO mark(title, country) VALUES ('Запорожец', 'Россия')
INSERT INTO mark_child(title, mark_id) VALUES ('название 1' , 1)
INSERT INTO mark_child(title, mark_id) VALUES ('название 2' , 2)

INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('290', 'red', 40000, 1, 1)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('290', 'orange', 30000, 3, 2)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('60', 'green', 5000, 2, 3)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('140', 'red', 3000, 1, 5)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('290', 'orange', 30000, 3, 4)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('60', 'green', 5000, 2, 1)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('290', 'red', 40000, 1, 1)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('290', 'orange', 30000, 3, 2)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('60', 'green', 5000, 2, 3)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('140', 'red', 3000, 4, 5)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('290', 'orange', 30500, 1, 4)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('60', 'green', 5500, 4, 1)

INSERT INTO ownership(owner_id, car_id) 
VALUES (1, 1)
INSERT INTO ownership(owner_id, car_id) 
VALUES (2, 2)
INSERT INTO ownership(owner_id, car_id) 
VALUES (3, 3)
INSERT INTO ownership(owner_id, car_id) 
VALUES (4, 4)
INSERT INTO ownership(owner_id, car_id) 
VALUES (5, 5)
INSERT INTO ownership(owner_id, car_id) 
VALUES (6, 6)
INSERT INTO ownership(owner_id, car_id) 
VALUES (7, 7)
INSERT INTO ownership(owner_id, car_id) 
VALUES (8, 8)
INSERT INTO ownership(owner_id, car_id) 
VALUES (1, 3)
INSERT INTO ownership(owner_id, car_id) 
VALUES (2, 4)
INSERT INTO ownership(owner_id, car_id) 
VALUES (3, 8)
INSERT INTO ownership(owner_id, car_id) 
VALUES (4, 8)

INSERT INTO refuelling(car_id, station_id) 
VALUES (1, 1)
INSERT INTO refuelling(car_id, station_id) 
VALUES (1, 2)
INSERT INTO refuelling(car_id, station_id) 
VALUES (2, 8)
INSERT INTO refuelling(car_id, station_id) 
VALUES (3, 7)
INSERT INTO refuelling(car_id, station_id) 
VALUES (4, 6)
INSERT INTO refuelling(car_id, station_id) 
VALUES (5, 5)
INSERT INTO refuelling(car_id, station_id) 
VALUES (6, 4)
INSERT INTO refuelling(car_id, station_id) 
VALUES (7, 3)
INSERT INTO refuelling(car_id, station_id) 
VALUES (8, 1)

create table person(name varchar(160) not null);
alter table person add primary key(name);
 
insert into person(name) values('Иванов');
insert into person(name) values('Петров');
insert into person(name) values('Сидоров');
insert into person(name) values('Федоров');

