INSERT INTO owners(title, age) VALUES ('Lapin Konstantine', 41)
INSERT INTO owners(title, age) VALUES ('Lapin Sergey', 70)
INSERT INTO owners(title, age) VALUES ('Vano', 31)
INSERT INTO owners(title)      VALUES ('"OOO Колхоз"')

INSERT INTO gas_stations(address) VALUES ('Будапештская')
INSERT INTO gas_stations(address) VALUES ('Гашека')

INSERT INTO parking_places(title) VALUES ('Подречная')
INSERT INTO parking_places(title) VALUES ('Сеновал')

INSERT INTO mark(title, country) VALUES ('mersedes', 'США')
INSERT INTO mark(title, country) VALUES ('Фиат', 'Россия')
INSERT INTO mark(title, country) VALUES ('mersedes', 'Россия')
INSERT INTO mark(title, country) VALUES ('ВАЗ', 'Russia')
INSERT INTO mark_child(title, country, mark_id) VALUES ('mersedes', 'Россия', 1)
INSERT INTO mark_child(title, country, mark_id) VALUES ('ВАЗ', 'Russia', 2)

INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('290', 'red', 40000, 1, 1)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('290', 'orange', 30000, 1, 1)
INSERT INTO cars(maxspeed, color, price, parking_id, mark_id) 
VALUES ('60', 'green', 5000, 2, 1)

INSERT INTO ownership(owner_id, car_id) 
VALUES (1, 1)
INSERT INTO ownership(owner_id, car_id) 
VALUES (2, 1)
INSERT INTO ownership(owner_id, car_id) 
VALUES (3, 2)
INSERT INTO ownership(owner_id, car_id) 
VALUES (4, 2)

INSERT INTO refuelling(car_id, station_id) 
VALUES (1, 1)
INSERT INTO refuelling(car_id, station_id) 
VALUES (1, 2)
INSERT INTO refuelling(car_id, station_id) 
VALUES (2, 2)