/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on 02.05.2010, 17:39:21
 */
package Karymov;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Антон
 */
public class MainForm extends javax.swing.JFrame implements IMainForm {

    Controller controller = null;
    FileDialog fdlg;

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        controller = new Controller(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        RunButton = new javax.swing.JButton();
        DebugButton = new javax.swing.JButton();
        StepNextButton = new javax.swing.JButton();
        StepOverButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPanel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsolePanel = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OpenMenuItem = new javax.swing.JMenuItem();
        SaveMenuItem = new javax.swing.JMenuItem();
        SaveAsMenuItem = new javax.swing.JMenuItem();
        RecentFilesMuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SaveButton.setText("Save");
        SaveButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveButtonMouseClicked(evt);
            }
        });
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        RunButton.setText("Run");
        RunButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RunButtonMouseClicked(evt);
            }
        });

        DebugButton.setText("Debug");
        DebugButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DebugButtonMouseClicked(evt);
            }
        });

        StepNextButton.setText("StepNext");
        StepNextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StepNextButtonMouseClicked(evt);
            }
        });

        StepOverButton.setText("StepOver");
        StepOverButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StepOverButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveButton)
                .addGap(18, 18, 18)
                .addComponent(RunButton)
                .addGap(55, 55, 55)
                .addComponent(DebugButton)
                .addGap(18, 18, 18)
                .addComponent(StepNextButton)
                .addGap(18, 18, 18)
                .addComponent(StepOverButton)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(RunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StepNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DebugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StepOverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TextPanel.setColumns(20);
        TextPanel.setRows(5);
        jScrollPane1.setViewportView(TextPanel);

        ConsolePanel.setColumns(20);
        ConsolePanel.setRows(5);
        jScrollPane2.setViewportView(ConsolePanel);

        jMenu1.setText("File");

        OpenMenuItem.setText("Open");
        OpenMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpenMenuItemMouseClicked(evt);
            }
        });
        OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(OpenMenuItem);

        SaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveMenuItem.setText("Save");
        SaveMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMenuItemMouseClicked(evt);
            }
        });
        jMenu1.add(SaveMenuItem);

        SaveAsMenuItem.setText("Save As...");
        SaveAsMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveAsMenuItemMouseClicked(evt);
            }
        });
        jMenu1.add(SaveAsMenuItem);

        RecentFilesMuItem.setText("Recent Files");
        RecentFilesMuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RecentFilesMuItemMouseClicked(evt);
            }
        });
        jMenu1.add(RecentFilesMuItem);

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMenuItemMouseClicked(evt);
            }
        });
        jMenu1.add(ExitMenuItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem6.setText("About");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveButtonMouseClicked
    }//GEN-LAST:event_SaveButtonMouseClicked

    private void RunButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RunButtonMouseClicked
    }//GEN-LAST:event_RunButtonMouseClicked

    private void DebugButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DebugButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_DebugButtonMouseClicked

    private void StepNextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StepNextButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StepNextButtonMouseClicked

    private void StepOverButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StepOverButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_StepOverButtonMouseClicked

    private void OpenMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpenMenuItemMouseClicked
        String fileName ="src/Karymov/programm.txt";
        TextPanel.setText(controller.openFile(fileName));
    }//GEN-LAST:event_OpenMenuItemMouseClicked

    private void SaveMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMenuItemMouseClicked
        String fileName ="src/Karymov/programm.txt";
        try {
            controller.saveFile(TextPanel.getText(), fileName);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveMenuItemMouseClicked

    private void SaveAsMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveAsMenuItemMouseClicked
    }//GEN-LAST:event_SaveAsMenuItemMouseClicked

    private void RecentFilesMuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RecentFilesMuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_RecentFilesMuItemMouseClicked

    private void ExitMenuItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMenuItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitMenuItemMouseClicked

    private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuItemActionPerformed
        String fileName ="src/Karymov/programm.txt";
        TextPanel.setText(controller.openFile(fileName));
    }//GEN-LAST:event_OpenMenuItemActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        String fileName ="src/Karymov/programm.txt";
        try {
            controller.saveFile(TextPanel.getText(), fileName);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_SaveButtonActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ConsolePanel;
    private javax.swing.JButton DebugButton;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JMenuItem RecentFilesMuItem;
    private javax.swing.JButton RunButton;
    private javax.swing.JMenuItem SaveAsMenuItem;
    private javax.swing.JButton SaveButton;
    private javax.swing.JMenuItem SaveMenuItem;
    private javax.swing.JButton StepNextButton;
    private javax.swing.JButton StepOverButton;
    private javax.swing.JTextArea TextPanel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void setTextInTextPanel(String text) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public String getTextInTextPanel() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setTextInConsolePanel(String text) {
        ConsolePanel.setText(text);
    }

    public String clearTextPanel() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public String clearConsolePanel() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
