/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PropertiesDialog.java
 *
 * Created on 11.11.2008, 3:56:57
 */
package j2se.g261.eda.automator.gui;

import j2se.g261.eda.automator.util.Globals;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author nastya
 */
public class PropertiesDialog extends javax.swing.JDialog {

    private static final String FILENAME = "fa.prop";
    private static final String LATEX = "latex";
    private static final String DVI = "dvi";
    private static final String DOT = "dot";
    private static final String IMAGE = "image";

    /** Creates new form PropertiesDialog */
    public PropertiesDialog(java.awt.Frame parent) {
        super(parent);
        initComponents();
        btnChooseLatex.addActionListener(new ChooseProgramActionListener(_tfLatex));
        btnChooseDot.addActionListener(new ChooseProgramActionListener(tfDot));
        btnChooseDvi.addActionListener(new ChooseProgramActionListener(tfDvi));
        btnChooseImage.addActionListener(new ChooseProgramActionListener(tfImgViewr));
        btnCancel.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                _tfLatex.setText("");
                tfDot.setText("");
                tfDvi.setText("");
                tfImgViewr.setText("");
                PropertiesDialog.this.dispose();
            }
        });

        btnSave.addActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                storeProperties();
                PropertiesDialog.this.dispose();
            }
        });
        Toolkit toolkit = Toolkit.getDefaultToolkit();
        Dimension screenSize = toolkit.getScreenSize();
        int x = (screenSize.width - getWidth()) / 2;
        int y = (screenSize.height - getHeight()) / 2;
        setLocation(x, y);
    }

    public void loadProperties() {
        try {
            Properties prop = new Properties();
            prop.load(new FileReader(new File(FILENAME)));
            Globals.DOT = prop.getProperty(DOT);
            tfDot.setText(Globals.DOT);
            Globals.DVI_VIEWER = prop.getProperty(DVI);
            tfDvi.setText(Globals.DVI_VIEWER);
            Globals.IMG_VIEWER = prop.getProperty(IMAGE);
            tfImgViewr.setText(Globals.IMG_VIEWER);
            Globals.LATEX_COMMAND = prop.getProperty(LATEX);
            _tfLatex.setText(Globals.LATEX_COMMAND);
        } catch (IOException ex) {
        }
    }

    private void storeProperties() {
        try {
            Properties prop = new Properties();
            prop.setProperty(LATEX, _tfLatex.getText());
            prop.setProperty(DVI, tfDvi.getText());
            prop.setProperty(DOT, tfDot.getText());
            prop.setProperty(IMAGE, tfImgViewr.getText());
            prop.store(new FileWriter(new File(FILENAME)), "Commands for " + "executing outernal programs like latex etc");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Write fail: permission denide.", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    @Override
    public void setVisible(boolean visible) {
        loadProperties();
        super.setVisible(visible);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        _tfLatex = new javax.swing.JTextField();
        tfDvi = new javax.swing.JTextField();
        tfDot = new javax.swing.JTextField();
        tfImgViewr = new javax.swing.JTextField();
        btnChooseLatex = new javax.swing.JButton();
        btnChooseDvi = new javax.swing.JButton();
        btnChooseDot = new javax.swing.JButton();
        btnChooseImage = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Properties");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Program paths", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel1.setText("Latex");

        jLabel2.setText("DVI Viewr");

        jLabel3.setText("Dot");

        jLabel4.setText("Image viewr");

        btnChooseLatex.setText("Choose");

        btnChooseDvi.setText("Choose");

        btnChooseDot.setText("Choose");

        btnChooseImage.setText("Choose");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfImgViewr, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(tfDvi, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(_tfLatex, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                    .addComponent(tfDot, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnChooseLatex)
                        .addComponent(btnChooseDvi)
                        .addComponent(btnChooseDot))
                    .addComponent(btnChooseImage))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(_tfLatex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseLatex))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfDvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseDvi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseDot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfImgViewr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseImage))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");

        btnSave.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                PropertiesDialog dialog = new PropertiesDialog(new javax.swing.JFrame());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    class ChooseProgramActionListener implements ActionListener {

        JTextField textField;

        ChooseProgramActionListener(JTextField textField) {
            this.textField = textField;
        }

        public void actionPerformed(ActionEvent e) {
            JFileChooser fc = new JFileChooser();
            fc.setFileSelectionMode(JFileChooser.FILES_ONLY);
            fc.setMultiSelectionEnabled(false);
            int result;
            if (!textField.getText().isEmpty()) {
                fc.setSelectedFile(new File(textField.getText()));
            }
            result = fc.showOpenDialog(PropertiesDialog.this);

            if (result == JFileChooser.APPROVE_OPTION) {
                textField.setText(fc.getSelectedFile().getAbsolutePath());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField _tfLatex;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnChooseDot;
    private javax.swing.JButton btnChooseDvi;
    private javax.swing.JButton btnChooseImage;
    private javax.swing.JButton btnChooseLatex;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tfDot;
    private javax.swing.JTextField tfDvi;
    private javax.swing.JTextField tfImgViewr;
    // End of variables declaration//GEN-END:variables
}
