CREATE TABLE "EXAM" 
( "EXAM_ID" NUMBER NOT NULL ENABLE, 
"NAME" VARCHAR2(200), 
CONSTRAINT "EXAM_PK" PRIMARY KEY ("EXAM_ID") ENABLE
)
/

CREATE TABLE "TEACHER" 
( "TEACHER_ID" NUMBER NOT NULL ENABLE, 
"EXAM_ID" NUMBER NOT NULL ENABLE,
"NAME" VARCHAR2(4000), 
CONSTRAINT "TEACHER_PK" PRIMARY KEY ("TEACHER_ID") ENABLE,
CONSTRAINT "TEACHER_FK" FOREIGN KEY ("EXAM_ID") 
REFERENCES "EXAM" ("EXAM_ID") ENABLE
)
/

CREATE TABLE "STUDENT" 
( "STUDENT_ID" NUMBER NOT NULL ENABLE, 
"NAME" VARCHAR2(4000), 
"ZA4ETKA_NUMBER" VARCHAR2(200), 
CONSTRAINT "STUDENT_PK" PRIMARY KEY ("STUDENT_ID") ENABLE
)
/

CREATE TABLE "STUDENT_EXAM" 
( "STUDENT_EXAM_ID" NUMBER NOT NULL ENABLE, 
"STUDENT_ID" NUMBER NOT NULL ENABLE, 
"EXAM_ID" NUMBER NOT NULL ENABLE, 
"MARK" NUMBER(1,0), 
CONSTRAINT "STUDENT_EXAM_PK" PRIMARY KEY ("STUDENT_EXAM_ID") ENABLE, 
CONSTRAINT "STUDENT_EXAM_FK" FOREIGN KEY ("STUDENT_ID")
REFERENCES "STUDENT" ("STUDENT_ID") ENABLE, 
CONSTRAINT "STUDENT_EXAM_FK2" FOREIGN KEY ("EXAM_ID")
REFERENCES "EXAM" ("EXAM_ID") ENABLE
)
/

 CREATE SEQUENCE   "FORALL"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/

CREATE OR REPLACE TRIGGER "BI_EXAM" 
before insert on "EXAM" 
for each row 
begin 
select "FORALL".nextval into :NEW.EXAM_ID from dual; 
end; 
/
ALTER TRIGGER "BI_EXAM" ENABLE
/

CREATE OR REPLACE TRIGGER "BI_STUDENT" 
before insert on "STUDENT" 
for each row 
begin 
select "FORALL".nextval into :NEW.STUDENT_ID from dual; 
end; 
/
ALTER TRIGGER "BI_STUDENT" ENABLE
/

CREATE OR REPLACE TRIGGER "BI_STUDENT_EXAM" 
before insert on "STUDENT_EXAM" 
for each row 
begin 
select "FORALL".nextval into :NEW.STUDENT_EXAM_ID from dual; 
end; 
/
ALTER TRIGGER "BI_STUDENT_EXAM" ENABLE
/

CREATE OR REPLACE TRIGGER "BI_TEACHER" 
before insert on "TEACHER" 
for each row 
begin 
select "FORALL".nextval into :NEW.TEACHER_ID from dual; 
end; 
/
ALTER TRIGGER "BI_TEACHER" ENABLE
/

create UNIQUE index "STUDENT_ZA4ETKA_UNQ"
 on "STUDENT" ("ZA4ETKA_NUMBER")
/   
