CREATE TABLE "TEACHER" 
( "TEACHER_ID" int IDENTITY (1,1) PRIMARY KEY,
"SUBJECT_ID" INT NOT NULL ENABLE,
"NAME" VARCHAR2(4000), 
CONSTRAINT "TEACHER_FK" FOREIGN KEY ("SUBJECT_ID")
REFERENCES "SUBJECT" ("SUBJECT_ID") ENABLE
)
/

CREATE TABLE "SUBJECT" 
( "SUBJECT_ID" int IDENTITY (1,1) PRIMARY KEY, 
"NAME" VARCHAR2(200), 
"TEACHER_ID" INT NOT NULL ENABLE, 
CONSTRAINT "SUBJECT_FK" FOREIGN KEY ("TEACHER_ID")
REFERENCES "TEACHER" ("TEACHER_ID") ENABLE
)
/

CREATE TABLE "SESSION" 
( "EXAM_ID" int IDENTITY (1,1) PRIMARY KEY, 
"SUBJECT_ID" INT FOREIGN KEY REFFERENCES "SUBJECT"("SUBJECT_ID"), 
"GROUP_ID" INT FOREIGN KEY REFERENCES "GROUPS"("GROUP_ID"), 
"DATE" DATETIME
)
/

CREATE TABLE "GROUPS" 
( "GROUP_ID" int IDENTITY (1,1) PRIMARY KEY, 
"STAROSTA_ID" INT NOT NULL ENABLE, 
"KURATOR_ID" INT NOT NULL ENABLE, 
CONSTRAINT "GROUPS_FK" FOREIGN KEY ("STAROSTA_ID")
REFERENCES "STUDENT" ("STUDENT_ID") ENABLE,
CONSTRAINT "GROUPS_FK2" FOREIGN KEY ("KURATOR_ID")
REFERENCES "TEACHER" ("TEACHER_ID") ENABLE,
)
/

CREATE TABLE "STUDENT" 
( "STUDENT_ID" int IDENTITY (1,1) PRIMARY KEY, 
"SEX" VARCHAR2(200),
"NAME" VARCHAR2(4000), 
"ZA4ETKA_NUMBER" VARCHAR2(200), 
)
/

CREATE TABLE "STUDENT_OCHNIK" 
( "STUDENT_OCH_ID" int IDENTITY (1,1) PRIMARY KEY, 
"SEX_OCH" VARCHAR2(200) REFERENCES STUDENT(SEX),
"NAME_OCH" VARCHAR2(4000) REFERENCES STUDENT(NAME), 
"ZA4ETKA_NUMBER_OCH" VARCHAR2(200) REFERENCES STUDENT(ZA4ETKA_NAMBER),
STEPENDIA VARCHAR(200)
)
/

CREATE TABLE "STUDENT_DISTANT" 
( "STUDENT_DIST_ID" int IDENTITY (1,1) PRIMARY KEY, 
"SEX_DIST" VARCHAR2(200) REFERENCES STUDENT(SEX),
"NAME_DIST" VARCHAR2(4000) REFERENCES STUDENT(NAME),
"MAIL_ADRESS@ VARCHAR2(4000)
)
/

CREATE TABLE "STUDENT_EXAM" 
( "STUDENT_EXAM_ID" int IDENTITY (1,1) PRIMARY KEY, 
"STUDENT_ID" NUMBER NOT NULL ENABLE, 
"EXAM_ID" NUMBER NOT NULL ENABLE, 
"MARK" NUMBER(1,0),  
CONSTRAINT "STUDENT_EXAM_FK" FOREIGN KEY ("STUDENT_ID")
REFERENCES "STUDENT" ("STUDENT_ID") ENABLE, 
CONSTRAINT "STUDENT_EXAM_FK2" FOREIGN KEY ("EXAM_ID")
REFERENCES "SESSION" ("EXAM_ID") ENABLE
)

/

