-- оличество студентов и студенток
SELECT SEX, COUNT(*) FROM STUDENT GROUP BY SEX;

--Ќомера зачеток студентов со средним баллом большим, чем 4.5.
SELECT zachetka, AVG(mark) 
FROM students, student_exam 
GROUP BY zachetka
HAVING AVG(mark) > 4.5;


SELECT SESSION.SUBJECT_ID, GROUPS.GROUP_ID FROM SESSION RIGHT JOIN GROUPS
ON SESSION.GROUP_ID = GROUPS.GROUP_ID;


SELECT SESSION.SUBJECT_ID, GROUPS.GROUP_ID FROM SESSION RIGHT JOIN GROUPS
ON SESSION.GROUP_ID = GROUPS.GROUP_ID;



SELECT SESSION.SUBJECT_ID, GROUPS.GROUP_ID FROM SESSION FULL JOIN GROUPS
ON SESSION.GROUP_ID = GROUPS.GROUP_ID;

SELECT SESSION.SUBJECT_ID, GROUPS.GROUP_ID FROM SESSION INNER JOIN GROUPS
ON SESSION.GROUP_ID = GROUPS.GROUP_ID;

SELECT SESSION.SUBJECT_ID, GROUPS.GROUP_ID FROM SESSION CROSS JOIN GROUPS
ON SESSION.GROUP_ID = GROUPS.GROUP_ID; 