/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainForm.java
 *
 * Created on 02.05.2010, 17:39:21
 */
package karymov;

import java.awt.FileDialog;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;

/**
 *
 * @author Антон
 */
public class MainForm extends javax.swing.JFrame implements IMainForm {

    Controller controller = null;
    String fileName;

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        controller = new Controller(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameFileChooser = new javax.swing.JFrame();
        FileChooser = new javax.swing.JFileChooser();
        FrameAbout = new javax.swing.JFrame();
        FirstDeveloper = new javax.swing.JLabel();
        SecondDeveloper = new javax.swing.JLabel();
        ThirdDeveloper = new javax.swing.JLabel();
        CloseAboutButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        SaveButton = new javax.swing.JButton();
        RunButton = new javax.swing.JButton();
        DebugButton = new javax.swing.JButton();
        StepNextButton = new javax.swing.JButton();
        StepOverButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextPanel = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsolePanel = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        OpenMenuItem = new javax.swing.JMenuItem();
        SaveMenuItem = new javax.swing.JMenuItem();
        SaveAsMenuItem = new javax.swing.JMenuItem();
        RecentFilesMuItem = new javax.swing.JMenuItem();
        ExitMenuItem = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        FrameFileChooser.setMinimumSize(new java.awt.Dimension(565, 389));

        FileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameFileChooserLayout = new javax.swing.GroupLayout(FrameFileChooser.getContentPane());
        FrameFileChooser.getContentPane().setLayout(FrameFileChooserLayout);
        FrameFileChooserLayout.setHorizontalGroup(
            FrameFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameFileChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        FrameFileChooserLayout.setVerticalGroup(
            FrameFileChooserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameFileChooserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        FrameAbout.setTitle("About");
        FrameAbout.setMinimumSize(new java.awt.Dimension(400, 300));

        FirstDeveloper.setText("FirstDeveloper");

        SecondDeveloper.setText("SecondDeveloper");

        ThirdDeveloper.setText("ThirdDeveloper");

        CloseAboutButton.setText("Close");
        CloseAboutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseAboutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout FrameAboutLayout = new javax.swing.GroupLayout(FrameAbout.getContentPane());
        FrameAbout.getContentPane().setLayout(FrameAboutLayout);
        FrameAboutLayout.setHorizontalGroup(
            FrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FrameAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FirstDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecondDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ThirdDeveloper, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
            .addGroup(FrameAboutLayout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(CloseAboutButton)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        FrameAboutLayout.setVerticalGroup(
            FrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FrameAboutLayout.createSequentialGroup()
                .addGroup(FrameAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SecondDeveloper, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(ThirdDeveloper, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(FirstDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addComponent(CloseAboutButton)
                .addGap(41, 41, 41))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Compiler");
        setMinimumSize(new java.awt.Dimension(565, 389));

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        RunButton.setText("Run");
        RunButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RunButtonMouseClicked(evt);
            }
        });
        RunButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RunButtonActionPerformed(evt);
            }
        });

        DebugButton.setText("Debug");
        DebugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebugButtonActionPerformed(evt);
            }
        });

        StepNextButton.setText("StepNext");
        StepNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepNextButtonActionPerformed(evt);
            }
        });

        StepOverButton.setText("StepOver");
        StepOverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StepOverButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SaveButton)
                .addGap(18, 18, 18)
                .addComponent(RunButton)
                .addGap(55, 55, 55)
                .addComponent(DebugButton)
                .addGap(18, 18, 18)
                .addComponent(StepNextButton)
                .addGap(18, 18, 18)
                .addComponent(StepOverButton)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(RunButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StepNextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DebugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StepOverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        TextPanel.setColumns(20);
        TextPanel.setRows(5);
        jScrollPane1.setViewportView(TextPanel);

        ConsolePanel.setColumns(20);
        ConsolePanel.setRows(5);
        jScrollPane2.setViewportView(ConsolePanel);

        jMenuBar1.setName(""); // NOI18N

        FileMenu.setText("File");

        OpenMenuItem.setText("Open");
        OpenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(OpenMenuItem);

        SaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        SaveMenuItem.setText("Save");
        SaveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(SaveMenuItem);

        SaveAsMenuItem.setText("Save As...");
        SaveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(SaveAsMenuItem);

        RecentFilesMuItem.setText("Recent Files");
        RecentFilesMuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecentFilesMuItemActionPerformed(evt);
            }
        });
        FileMenu.add(RecentFilesMuItem);

        ExitMenuItem.setText("Exit");
        ExitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitMenuItem(evt);
            }
        });
        FileMenu.add(ExitMenuItem);

        jMenuBar1.add(FileMenu);

        HelpMenu.setText("Help");

        jMenuItem6.setText("About");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutActionPerformed(evt);
            }
        });
        HelpMenu.add(jMenuItem6);

        jMenuBar1.add(HelpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenMenuItemActionPerformed
        FrameFileChooser.setTitle("Open File");
        FrameFileChooser.show();
        FileChooser.setVisible(true);
//        String fileName ="src/Karymov/programm.txt";
//        TextPanel.setText(controller.openFile(fileName));

    }//GEN-LAST:event_OpenMenuItemActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        //String fileName ="src/Karymov/programm.txt";
        try {
            controller.saveFile(TextPanel.getText(), fileName);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_SaveButtonActionPerformed
    }
        private void ExitMenuItem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitMenuItem

            //int beforeEscapeHight=Memento.getMemento().getHeight();
            int beforeEscapeHight=MainForm.this.getHeight();
            String settingDirectory ="src/Karymov/setting.txt" ;
            ParseSetting.writeHeight(settingDirectory,ParseSetting.setHeight(beforeEscapeHight));
         //   System.out.println(Memento.getMemento().getHeight());
            System.exit(0);
        }//GEN-LAST:event_ExitMenuItem

        private void RunButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RunButtonActionPerformed

            //controller.runProgram(TextPanel.getText());
        }//GEN-LAST:event_RunButtonActionPerformed

        private void CloseAboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseAboutButtonActionPerformed
            FrameAbout.hide();
        }//GEN-LAST:event_CloseAboutButtonActionPerformed

        private void AboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutActionPerformed
            FrameAbout.show();
            FirstDeveloper.setVisible(true);
            SecondDeveloper.setVisible(true);
            ThirdDeveloper.setVisible(true);
            CloseAboutButton.setVisible(true);
        }//GEN-LAST:event_AboutActionPerformed

        private void DebugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebugButtonActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_DebugButtonActionPerformed

        private void StepNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepNextButtonActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_StepNextButtonActionPerformed

        private void StepOverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StepOverButtonActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_StepOverButtonActionPerformed

        private void SaveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveMenuItemActionPerformed
            try {
                controller.saveFile(TextPanel.getText(), fileName);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }//GEN-LAST:event_SaveMenuItemActionPerformed
    }
        private void SaveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsMenuItemActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_SaveAsMenuItemActionPerformed

        private void RecentFilesMuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecentFilesMuItemActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_RecentFilesMuItemActionPerformed

        private void FileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FileChooserActionPerformed
            fileName = FileChooser.getSelectedFile().getPath();
            TextPanel.setText(controller.openFile(fileName));
            FrameFileChooser.hide();
        }//GEN-LAST:event_FileChooserActionPerformed

        private void RunButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RunButtonMouseClicked
            setTextInConsolePanel(controller.runProgram(TextPanel.getText()));
        }//GEN-LAST:event_RunButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception exception) {}
                MainForm mainForm = new MainForm();
                mainForm.TextPanel.setFont(new Font("Times New Roman",Font.BOLD,14));
                mainForm.ConsolePanel.setFont(new Font("Times New Roman",Font.BOLD,14));
                String settingDirectory ="src/Karymov/setting.txt" ;
                int height = ParseSetting.getHeight(ParseSetting.findHeight(settingDirectory));
                mainForm.setSize(150,height);
                mainForm.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseAboutButton;
    private javax.swing.JTextArea ConsolePanel;
    private javax.swing.JButton DebugButton;
    private javax.swing.JMenuItem ExitMenuItem;
    private javax.swing.JFileChooser FileChooser;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JLabel FirstDeveloper;
    private javax.swing.JFrame FrameAbout;
    private javax.swing.JFrame FrameFileChooser;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JMenuItem OpenMenuItem;
    private javax.swing.JMenuItem RecentFilesMuItem;
    private javax.swing.JButton RunButton;
    private javax.swing.JMenuItem SaveAsMenuItem;
    private javax.swing.JButton SaveButton;
    private javax.swing.JMenuItem SaveMenuItem;
    private javax.swing.JLabel SecondDeveloper;
    private javax.swing.JButton StepNextButton;
    private javax.swing.JButton StepOverButton;
    private javax.swing.JTextArea TextPanel;
    private javax.swing.JLabel ThirdDeveloper;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void setTextInTextPanel(String text) {
        TextPanel.setText(text);
    }

    public String getTextInTextPanel() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    public void setTextInConsolePanel(String text) {
        ConsolePanel.setText(text);
    }

    public void clearTextPanel() {
        TextPanel.setText(null);
    }

    public void clearConsolePanel() {
        ConsolePanel.setText(null);
    }

    public void printInConsole(String text) {
        ConsolePanel.setText(text);
    }
}
