package Database;

import java.io.IOException;
import java.io.File;

public class Generator {
	public static void main(String[] args) throws Exception {
		FilmsTable table = new FilmsTable();
		
		File f = new File(table.getFilename());
		f.delete();
		
table.insert(new Film("Tout le monde il est beau, tout le monde il est gentil", "1972"));
table.insert(new Film("Maid in Manhattan", "2002"));
table.insert(new Film("Dragonfly", "2002"));
table.insert(new Film("Windtalkers", "2002"));
table.insert(new Film("Red Dragon", "2002"));
table.insert(new Film("Girl Fever", "2002"));
table.insert(new Film("Equilibrium", "2002"));
table.insert(new Film("Daredevil", "2003"));
table.insert(new Film("Dolls", "2002"));
table.insert(new Film("House on Turk Street, The", "2002"));
table.insert(new Film("Lundi matin", "2002"));
table.insert(new Film("Avenging Angelo", "2002"));
table.insert(new Film("White Oleander", "2002"));
table.insert(new Film("Vie promise, La", "2002"));
table.insert(new Film("Enough", "2002"));
table.insert(new Film("Minority Report", "2002"));
table.insert(new Film("Scorched", "2003"));
table.insert(new Film("xXx", "2002"));
table.insert(new Film("Lord of the Rings: The Two Towers, The", "2002"));
table.insert(new Film("Insomnia", "2002"));
table.insert(new Film("Die Another Day", "2002"));
table.insert(new Film("Darkness", "2002"));
table.insert(new Film("Tattoo", "2002"));
table.insert(new Film("Two Weeks Notice", "2002"));
table.insert(new Film("National Security", "2003"));
table.insert(new Film("Men in Black 2", "2002"));
table.insert(new Film("Harry Potter and the Chamber of Secrets", "2002"));
table.insert(new Film("Sum of All Fears, The", "2002"));
table.insert(new Film("Catch Me If You Can", "2002"));
table.insert(new Film("Secretary", "2002"));
table.insert(new Film("Ballistic: Ecks vs Sever", "2002"));
table.insert(new Film("Dark Blue", "2002"));
table.insert(new Film("Solaris", "2002"));
table.insert(new Film("Old Men In New Cars", "2002"));
table.insert(new Film("City by the Sea", "2002"));
table.insert(new Film("Stuart Little 2", "2002"));
table.insert(new Film("FearDotCom", "2002"));
table.insert(new Film("Stuart Little", "1999"));
table.insert(new Film("Formula 51 (51st State, The)", "2001"));
table.insert(new Film("Tuxedo,The", "2002"));
table.insert(new Film("The Last Minute", "2001"));
table.insert(new Film("Nick Of Time", "1995"));
table.insert(new Film("Donnie Brasco", "1997"));
table.insert(new Film("Ring, The", "2002"));
table.insert(new Film("Frida", "2002"));
table.insert(new Film("Diables, Les", "2002"));
table.insert(new Film("Dog Soldiers", "2002"));
table.insert(new Film("8 Mile", "2002"));
table.insert(new Film("Jet Lag", "2002"));
table.insert(new Film("Rue Des Plaisirs", "2002"));
table.insert(new Film("And Now... Ladies and Gentlemen...", "2002"));
table.insert(new Film("Atlantis: The Lost Empire", "2001"));
table.insert(new Film("Lilo & Stitch", "2002"));
table.insert(new Film("On_Line", "2002"));
table.insert(new Film("Embrassez qui vous voudrez", "2002"));
table.insert(new Film("Transporter, The", "2002"));
table.insert(new Film("Sweet Home Alabama", "2002"));
table.insert(new Film("Donnie Darko", "2001"));
table.insert(new Film("Sirene rouge, La", "2002"));
table.insert(new Film("Monique", "2002"));
table.insert(new Film("I Spy", "2002"));
table.insert(new Film("Rules of Attraction, The", "2002"));
table.insert(new Film("Spy Kids 2: Island of Lost Dreams", "2002"));
table.insert(new Film("S1m0ne", "2002"));
table.insert(new Film("Extreme Ops", "2002"));
table.insert(new Film("Ghost Ship", "2002"));
table.insert(new Film("Demonlover", "2002"));
table.insert(new Film("Chicago", "2002"));
table.insert(new Film("Return to Never Land", "2002"));
table.insert(new Film("Copycat", "1995"));
table.insert(new Film("Princess Diaries, The", "2001"));
table.insert(new Film("Treasure Planet", "2002"));
table.insert(new Film("Taxi 3", "2002"));
table.insert(new Film("Analyze That", "2002"));
table.insert(new Film("Gangs of New York", "2002"));
table.insert(new Film("About Schmidt", "2002"));
table.insert(new Film("Hours, The", "2002"));
table.insert(new Film("Confessions of a Dangerous Mind", "2002"));
table.insert(new Film("Hot Chick, The", "2002"));
table.insert(new Film("Adaptation.", "2002"));
table.insert(new Film("Just Married", "2003"));
table.insert(new Film("Hunted, The", "2003"));
table.insert(new Film("Johnny English", "2003"));
table.insert(new Film("Core, The", "2003"));
table.insert(new Film("Phone Booth", "2002"));
table.insert(new Film("Final Destination 2", "2003"));
table.insert(new Film("Shanghai Knights", "2003"));
table.insert(new Film("Jeffrey", "1995"));
table.insert(new Film("Mies vailla menneisyytta", "2002"));
table.insert(new Film("More Ants in the Pants", "2002"));
table.insert(new Film("102 Dalmatians", "2000"));
table.insert(new Film("Jungle Book 2, The", "2003"));
table.insert(new Film("View from the Top, A", "2003"));
table.insert(new Film("Boat Trip", "2003"));
table.insert(new Film("X2", "2003"));
table.insert(new Film("Pianist, The", "2002"));
table.insert(new Film("Matrix Reloaded, The", "2003"));
table.insert(new Film("Quiet American, The", "2002"));
table.insert(new Film("Lilya 4-Ever", "2002"));
table.insert(new Film("Try Seventeen", "2002"));
table.insert(new Film("Jackass: The Movie", "2002"));
table.insert(new Film("Tears of the Sun", "2003"));
table.insert(new Film("Darkness Falls", "2003"));
table.insert(new Film("Death and the Maiden", "1994"));
table.insert(new Film("Novo", "2002"));
table.insert(new Film("Magdalene Sisters, The", "2002"));
table.insert(new Film("Sur mes levres", "2001"));
table.insert(new Film("Loving Father, A /", "2002"));
table.insert(new Film("Open Hearts", "2002"));
table.insert(new Film("Quo Vadis?", "2001"));
table.insert(new Film("Snows Of Kilimanjaro, The", "1952"));
table.insert(new Film("Recruit, The", "2003"));
table.insert(new Film("Gerry", "2002"));
table.insert(new Film("Dreamcatcher", "2003"));
table.insert(new Film("Basic", "2003"));
table.insert(new Film("How to Lose a Guy in 10 Days", "2003"));
table.insert(new Film("Fanfan la tulipe", "2003"));
table.insert(new Film("Hulk", "2003"));
table.insert(new Film("Anger Management", "2003"));
table.insert(new Film("Hero / Ying xiong", "2002"));
table.insert(new Film("Honogurai mizu no soko kara", "2002"));
table.insert(new Film("Crime Spree", "2003"));
table.insert(new Film("Terminator 3: Rise of the Machines", "2003"));
table.insert(new Film("Lara Croft Tomb Raider: The Cradle of Life", "2003"));
table.insert(new Film("Bulletproof Monk", "2003"));
table.insert(new Film("Man Apart, A", "2003"));
table.insert(new Film("Daddy Day Care", "2003"));
table.insert(new Film("Seabiscuit", "2003"));
table.insert(new Film("Confidence", "2003"));
table.insert(new Film("Naqoyqatsi", "2002"));
table.insert(new Film("Euro Pudding", "2002"));
table.insert(new Film("Carolina", "2003"));
table.insert(new Film("Oasis", "2002"));
table.insert(new Film("Hotel", "2001"));
table.insert(new Film("Chouchou", "2003"));
table.insert(new Film("Pirates of the Caribbean: The Curse of the Black Pearl", "2003"));
table.insert(new Film("Dogville", "2003"));
table.insert(new Film("Snow Falling on Cedars", "1999"));
table.insert(new Film("Below", "2002"));
table.insert(new Film("He loves me, he loves me not", "2002"));
table.insert(new Film("Nowhere in Africa", "2001"));
table.insert(new Film("Importance of Being Earnest, The", "2002"));
table.insert(new Film("Callas Forever", "2002"));
table.insert(new Film("Leave Your Hands on My Hips", "2003"));
table.insert(new Film("Far from Heaven", "2002"));
table.insert(new Film("Life of David Gale, The", "2003"));
table.insert(new Film("Dirty Pretty Things", "2002"));
table.insert(new Film("Bloody Mallory", "2002"));
table.insert(new Film("Good bye, Lenin!", "2003"));
table.insert(new Film("Ken Park", "2002"));
table.insert(new Film("Walls of Glass", "1983"));
table.insert(new Film("Mon idole", "2003"));
table.insert(new Film("House of 1000 Corpses ", "2003"));
table.insert(new Film("Dumb and Dumberer: When Harry Met Lloyd", "2003"));
table.insert(new Film("Agent Cody Banks", "2003"));
table.insert(new Film("Sinbad: Legend of the Seven Seas", "2003"));
table.insert(new Film("Identity", "2003"));
table.insert(new Film("Enfants de la pluie, Les", "2003"));
table.insert(new Film("Spun", "2002"));
table.insert(new Film("Young Adam", "2003"));
table.insert(new Film("Moi Cesar, 10 ans 1/2, 1m39", "2003"));
table.insert(new Film("Party Monster", "2003"));
table.insert(new Film("Bienvenue chez les Rozes", "2003"));
table.insert(new Film("In-Laws, The", "2003"));
table.insert(new Film("Katakuri-ke no kofuku", "2002"));
table.insert(new Film("Balzac et la petite tailleuse chinoise / Xiao cai feng", "2002"));
table.insert(new Film("Down with Love", "2003"));
table.insert(new Film("Father and Son", "2003"));
table.insert(new Film("Time of the Wolf, The", "2005"));
table.insert(new Film("S.W.A.T.", "2003"));
table.insert(new Film("Bruce Almighty", "2003"));
table.insert(new Film("American Wedding", "2003"));
table.insert(new Film("Italian Job, The", "2003"));
table.insert(new Film("Jonah: A VeggieTales Movie", "2002"));
table.insert(new Film("Bend It Like Beckham", "2002"));
table.insert(new Film("Hollywood Homicide", "2003"));
table.insert(new Film("Wrong Turn", "2003"));
table.insert(new Film("League of Extraordinary Gentlemen, The", "2003"));
table.insert(new Film("Underworld", "2003"));
table.insert(new Film("Once Upon a Time in Mexico", "2003"));
table.insert(new Film("Matrix Revolutions, The", "2003"));
table.insert(new Film("Open Range", "2003"));
table.insert(new Film("Bad Boys II", "2003"));
table.insert(new Film("Jeepers Creepers II", "2003"));
table.insert(new Film("The Year of Living Dangerously", "1982"));
table.insert(new Film("Matchstick Men", "2003"));
table.insert(new Film("Triplettes de Belleville, Les", "2003"));
table.insert(new Film("Legally Blonde 2: Red, White & Blonde", "2003"));
table.insert(new Film("Spy Kids 3-D: Game Over", "2003"));
table.insert(new Film("Swimming Pool", "2003"));
table.insert(new Film("Kaena: The Prophecy", "2003"));
table.insert(new Film("Deathwatch", "2002"));
table.insert(new Film("Barbarian Invasions, The", "2003"));
table.insert(new Film("Fear X", "2003"));
table.insert(new Film("Interstella 5555: The 5tory of the 5ecret 5tar 5ystem", "2003"));
table.insert(new Film("Antikiller 2: Antiterror", "2003"));
table.insert(new Film("Vozvrashcheniye", "2003"));
table.insert(new Film("Battle Royale II", "2003"));
table.insert(new Film("Freaky Friday", "2003"));
table.insert(new Film("Jesus", "1979"));
table.insert(new Film("Intolerable Cruelty", "2003"));
table.insert(new Film("Medallion, The", "2003"));
table.insert(new Film("Kill Bill: Vol. 1", "2003"));
table.insert(new Film("Divorce, Le", "2003"));
table.insert(new Film("Raising Victor Vargas", "2002"));
table.insert(new Film("Looney Tunes: Back in Action", "2003"));
table.insert(new Film("Runaway Jury", "2003"));
table.insert(new Film("Finding Nemo", "2003"));
table.insert(new Film("Scary Movie 3", "2003"));
table.insert(new Film("Freddy Vs. Jason", "2003"));
table.insert(new Film("Out of Time", "2003"));
table.insert(new Film("Rundown, The", "2003"));
table.insert(new Film("Embalmer, The", "2002"));
table.insert(new Film("Love Actually", "2002"));
table.insert(new Film("Virgen de la lujuria, La", "2002"));
table.insert(new Film("Tais-toi!", "2003"));
table.insert(new Film("Bad Santa", "2003"));
table.insert(new Film("Cabin Fever", "2002"));
table.insert(new Film("To Kill a King", "2003"));
table.insert(new Film("Noi the Albino", "2003"));
table.insert(new Film("Love the Hard Way", "2001"));
table.insert(new Film("Plots with a View", "2002"));
table.insert(new Film("Lord of the Rings: The Return of the King, The", "2003"));
table.insert(new Film("Uzak", "2002"));
table.insert(new Film("Uptown Girls", "2002"));
table.insert(new Film("Papillon, Le", "2002"));
table.insert(new Film("Lost in Translation", "2003"));
table.insert(new Film("Duplex", "2003"));
table.insert(new Film("Haunted Mansion, The", "2003"));
table.insert(new Film("Stuck on You", "2003"));
table.insert(new Film("28 Days Later...", "2002"));
table.insert(new Film("Gothika", "2003"));
table.insert(new Film("Dragon Hill", "2002"));
table.insert(new Film("Michel Vaillant", "2003"));
table.insert(new Film("Mail Order Bride", "2003"));
table.insert(new Film("Petite Lili, La", "2003"));
table.insert(new Film("Nowhere to Go But Up", "2003"));
table.insert(new Film("Grill Point / Halbe Treppe", "2002"));
table.insert(new Film("Carmen", "2003"));
table.insert(new Film("Dans ma peau", "2002"));
table.insert(new Film("Tasogare Seibei", "2002"));
table.insert(new Film("Gomez & Tavares", "2003"));
table.insert(new Film("White Gold", "2003"));
table.insert(new Film("Alex & Emma", "2003"));
table.insert(new Film("The Hard Word ", "2002"));
table.insert(new Film("Cheaper by the Dozen", "2003"));
table.insert(new Film("Bom yeoreum gaeul gyeoul geurigo bom", "2003"));
table.insert(new Film("Hae anseon / Coast Guard", "2002"));
table.insert(new Film("Stupeur et tremblements", "2003"));
table.insert(new Film("Last Samurai, The", "2003"));
table.insert(new Film("Human Stain, The", "2003"));
table.insert(new Film("Texas Chainsaw Massacre, The", "2003"));
table.insert(new Film("House of Sand and Fog", "2003"));
table.insert(new Film("Tiptoes", "2003"));
table.insert(new Film("Paycheck", "2003"));
table.insert(new Film("Mystic River", "2003"));
table.insert(new Film("Twentynine Palms", "2003"));
table.insert(new Film("Big Fish", "2003"));
table.insert(new Film("School of Rock, The", "2003"));
table.insert(new Film("Dreamers,The", "2003"));
table.insert(new Film("7 ans de mariage", "2003"));
table.insert(new Film("Otro lado de la cama, El", "2002"));
table.insert(new Film("Butterfly Effect, The", "2004"));
table.insert(new Film("Cold Mountain", "2003"));
table.insert(new Film("House of the Dead", "2003"));
table.insert(new Film("50 First Dates", "2004"));
table.insert(new Film("21 Grams", "2003"));
table.insert(new Film("Good Boy!", "2003"));
table.insert(new Film("Torque", "2004"));
table.insert(new Film("Peter Pan", "2003"));
table.insert(new Film("Hidalgo", "2004"));
table.insert(new Film("Monster", "2003"));
table.insert(new Film("Elf", "2003"));
table.insert(new Film("Blueberry", "2004"));
table.insert(new Film("Honey", "2003"));
table.insert(new Film("25 degres en hiver", "2004"));
table.insert(new Film("Brother Bear", "2003"));
table.insert(new Film("Cat in the Hat, The", "2003"));
table.insert(new Film("Chin gei bin", "2003"));
table.insert(new Film("RRRrrrr!!!", "2004"));
table.insert(new Film("Along Came Polly", "2004"));
table.insert(new Film("Secret Window", "2004"));
table.insert(new Film("Taking Lives", "2004"));
table.insert(new Film("Ni pour, ni contre (bien au contraire)", "2003"));
table.insert(new Film("Cidade de Deus", "2002"));
table.insert(new Film("Imagining Argentina", "2003"));
table.insert(new Film("Passion of the Christ, The", "2004"));
table.insert(new Film("Dawn of the Dead", "2004"));
table.insert(new Film("Starsky & Hutch", "2004"));
table.insert(new Film("Scooby Doo 2: Monsters Unleashed", "2004"));
table.insert(new Film("Zatoichi", "2003"));
table.insert(new Film("Dirty Dancing: Havana Nights", "2004"));
table.insert(new Film("Bon voyage", "2003"));
table.insert(new Film("Timeline", "2003"));
table.insert(new Film("Eternal Sunshine of the Spotless Mind", "2004"));
table.insert(new Film("Fallo!", "2003"));
table.insert(new Film("Agent Cody Banks 2: Destination London", "2004"));
table.insert(new Film("Twisted", "2004"));
table.insert(new Film("Janis et John", "2003"));
table.insert(new Film("Mona Lisa Smile", "2003"));
table.insert(new Film("Ned Kelly", "2003"));
table.insert(new Film("Igry motylkov", "2004"));
table.insert(new Film("Mauvais esprit", "2003"));
table.insert(new Film("Kiss of Life", "2003"));
table.insert(new Film("Cooler, The", "2003"));
table.insert(new Film("Fei ying", "2004"));
table.insert(new Film("Girl Next Door, The", "2004"));
table.insert(new Film("Last Life in the Universe", "2003"));
table.insert(new Film("Cid: La leyenda, El", "2003"));
table.insert(new Film("Jersey Girl", "2004"));
table.insert(new Film("Bowling for Columbine", "2002"));
table.insert(new Film("Falling Angels", "2003"));
table.insert(new Film("Ju-on: The Grudge", "2003"));
table.insert(new Film("Van Helsing", "2004"));
table.insert(new Film("Hackers", "1995"));
table.insert(new Film("Foxfire", "1996"));
table.insert(new Film("Troy", "2004"));
table.insert(new Film("Day After Tomorrow, The", "2004"));
table.insert(new Film("Win a Date with Tad Hamilton!", "2004"));
table.insert(new Film("Achtung, fertig, Charlie!", "2003"));
table.insert(new Film("Immortel (ad vitam)", "2004"));
table.insert(new Film("Reconstruction", "2003"));
table.insert(new Film("Harry Potter and the Prisoner of Azkaban", "2004"));
table.insert(new Film("Laws of Attraction", "2004"));
table.insert(new Film("Godsend", "2004"));
table.insert(new Film("Hymypoika", "2003"));
table.insert(new Film("Raising Helen", "2004"));
table.insert(new Film("Kill Bill: Vol. 2", "2004"));
table.insert(new Film("American Splendor", "2003"));
table.insert(new Film("Spartan", "2004"));
table.insert(new Film("Spider-Man 2", "2004"));
table.insert(new Film("Spider-Man", "2002"));
table.insert(new Film("Mean Girls", "2004"));
table.insert(new Film("Prince & Me, The", "2004"));
table.insert(new Film("Agents secrets", "2004"));
table.insert(new Film("Punisher, The", "2004"));
table.insert(new Film("Connie and Carla", "2002"));
table.insert(new Film("Ella Enchanted", "2004"));
table.insert(new Film("Mindhunters", "2003"));
table.insert(new Film("Stepford Wives, The", "2004"));
table.insert(new Film("Ripoux 3", "2004"));
table.insert(new Film("Voditel dlya Very", "2004"));
table.insert(new Film("Shrek", "2001"));
table.insert(new Film("Walking Tall", "2004"));
table.insert(new Film("13 Going on 30", "2004"));
table.insert(new Film("New York Minute", "2004"));
table.insert(new Film("Tube", "2003"));
table.insert(new Film("Gegen die Wand", "2004"));
table.insert(new Film("Finestra di fronte, La", "2003"));
table.insert(new Film("I, Robot", "2004"));
table.insert(new Film("Elephant", "2003"));
table.insert(new Film("Shiza", "2004"));
table.insert(new Film("Mysterium Occupation", "2004"));
table.insert(new Film("Chakushin ari", "2003"));
table.insert(new Film("Shrek 2", "2004"));
table.insert(new Film("King Arthur", "2004"));
table.insert(new Film("Garfield", "2004"));
table.insert(new Film("Roger Dodger", "2002"));
table.insert(new Film("Around the World in 80 Days", "2004"));
table.insert(new Film("Coffee and Cigarettes", "2003"));
table.insert(new Film("Nathalie...", "2003"));
table.insert(new Film("National Lampoon Presents Dorm Daze", "2003"));
table.insert(new Film("Eurotrip", "2004"));
table.insert(new Film("Bourne Supremacy, The", "2004"));
table.insert(new Film("Farenheit 9/11", "2004"));
table.insert(new Film("Zivot je cudo", "2004"));
table.insert(new Film("Hellboy", "2004"));
table.insert(new Film("Whole Ten Yards, The", "2004"));
table.insert(new Film("Terminal, The", "2004"));
table.insert(new Film("Village, The", "2004"));
table.insert(new Film("Man on Fire", "2004"));
table.insert(new Film("Chronicles of Riddick, The", "2004"));
table.insert(new Film("Thunderbirds", "2004"));
table.insert(new Film("Cinderella Story, A", "2004"));
table.insert(new Film("Wimbledon", "2004"));
table.insert(new Film("Romasanta", "2004"));
table.insert(new Film("11:14", "2003"));
table.insert(new Film("Gin gwai 2", "2004"));
table.insert(new Film("Harold & Kumar Go to White Castle", "2004"));
table.insert(new Film("Double zero", "2004"));
table.insert(new Film("Dodgeball: A True Underdog Story", "2004"));
table.insert(new Film("Collateral", "2004"));
table.insert(new Film("Ogu and Mampato in Rapa Nui", "2002"));
table.insert(new Film("De-Lovely", "2004"));
table.insert(new Film("Sky Captain and the World of Tomorrow", "2004"));
table.insert(new Film("White Chicks", "2004"));
table.insert(new Film("Open Water", "2003"));
table.insert(new Film("Notebook, The", "2004"));
table.insert(new Film("AVP: Alien vs. Predator", "2004"));
table.insert(new Film("Anacondas: The Hunt for the Blood Orchid", "2004"));
table.insert(new Film("Catwoman", "2004"));
table.insert(new Film("Shark Tale", "2004"));
table.insert(new Film("Adventures of Pluto Nash, The", "2002"));
table.insert(new Film("My Big Fat Greek Wedding", "2002"));
table.insert(new Film("Signs", "2002"));
table.insert(new Film("Boginya: kak ya polyubila", "2004"));
table.insert(new Film("Wonderful Days", "2004"));
table.insert(new Film("Madhouse", "2004"));
table.insert(new Film("Home on the Range", "2004"));
table.insert(new Film("Pas sur la bouche", "2003"));
table.insert(new Film("Tuner, The", "2004"));
table.insert(new Film("Ju-on: The Grudge 2", "2003"));
table.insert(new Film("Monsters, Inc.", "2001"));
table.insert(new Film("Jagoda u supermarketu", "2003"));
table.insert(new Film("Dependencia sexual / Sexual dependency", "2003"));
table.insert(new Film("Shall We Dance?", "2004"));
table.insert(new Film("Cellular", "2004"));
table.insert(new Film("Without a Paddle", "2004"));
table.insert(new Film("Resident Evil: Apocalypse", "2004"));
table.insert(new Film("Ladder 49", "2004"));
table.insert(new Film("Alexander", "2004"));
table.insert(new Film("Bridget Jones: The Edge of Reason", "2004"));
table.insert(new Film("Head in the Clouds", "2004"));
table.insert(new Film("Bourne Identity, The", "2002"));
table.insert(new Film("Mars", "2004"));
table.insert(new Film("Fils du vent, Les", "2004"));
table.insert(new Film("Anchorman: The Legend of Ron Burgundy", "2004"));
table.insert(new Film("Paparazzi", "2004"));
table.insert(new Film("Princess Diaries 2: Royal Engagement, The", "2004"));
table.insert(new Film("Love Me If You Dare", "2003"));
table.insert(new Film("Liegen lernen", "2003"));
table.insert(new Film("Girl with a Pearl Earring", "2003"));
table.insert(new Film("Cookout, The", "2004"));
table.insert(new Film("Grudge, The", "2004"));
table.insert(new Film("Forgotten, The", "2004"));
table.insert(new Film("Incredibles, The", "2004"));
table.insert(new Film("National Treasure", "2004"));
table.insert(new Film("Reyes magos, Los", "2003"));
table.insert(new Film("San-Antonio", "2004"));
table.insert(new Film("Alfie", "2004"));
table.insert(new Film("Surviving Christmas", "2004"));
table.insert(new Film("Polar Express, The", "2004"));
table.insert(new Film("Tooth", "2004"));
table.insert(new Film("Christmas with the Kranks", "2004"));
table.insert(new Film("Taxi", "2004"));
table.insert(new Film("5x2", "2004"));
table.insert(new Film("After the Sunset", "2004"));
table.insert(new Film("Bin-jip", "2004"));
table.insert(new Film("Phantom of the Opera, The", "2004"));
table.insert(new Film("Pinocchio 3000", "2004"));
table.insert(new Film("Wicker Park", "2004"));
table.insert(new Film("Saw", "2004"));
table.insert(new Film("Vanity Fair", "2004"));
table.insert(new Film("Meet the Fockers", "2004"));
table.insert(new Film("Shi mian mai fu", "2004"));
table.insert(new Film("Ray", "2004"));
table.insert(new Film("2046", "2004"));
table.insert(new Film("Comme une image", "2004"));
table.insert(new Film("He ni zai yi qi", "2002"));
table.insert(new Film("Somersault", "2004"));
table.insert(new Film("Flight of the Phoenix", "2004"));
table.insert(new Film("Aviator, The", "2004"));
table.insert(new Film("Finding Neverland", "2004"));
table.insert(new Film("Team America: World Police", "1998"));
table.insert(new Film("Banlieue 13", "2004"));
table.insert(new Film("Assault on Precinct 13", "2005"));
table.insert(new Film("Closer", "2004"));
table.insert(new Film("Seed of Chucky", "2004"));
table.insert(new Film("Blade: Trinity", "2004"));
table.insert(new Film("You I love", "2003"));
table.insert(new Film("El tesoro de las Cuatro Coronas", "1982"));
table.insert(new Film("Sansa", "2004"));
table.insert(new Film("Feux rouges", "2004"));
table.insert(new Film("Dare mo shiranai", "2004"));
table.insert(new Film("? ton image", "2004"));
table.insert(new Film("Hide and Seek", "2005"));
table.insert(new Film("Hostage", "2005"));
table.insert(new Film("Spanglish", "2004"));
table.insert(new Film("White Noise", "2005"));
table.insert(new Film("New Police Story", "2004"));
table.insert(new Film("Love Object", "2003"));
table.insert(new Film("Bride & Prejudice", "2005"));
table.insert(new Film("My Tube!", "2008"));
table.insert(new Film("The heart is else where / Il Cuore Altrove", "2003"));
table.insert(new Film("Panic Room", "2002"));
table.insert(new Film("Sideways", "2004"));
table.insert(new Film("Boy s tenyu", "2005"));
table.insert(new Film("Cursed", "2005"));
table.insert(new Film("In good company", "2004"));
table.insert(new Film("Hitch", "2005"));
table.insert(new Film("Elektra", "2005"));
table.insert(new Film("Merchant of Venice, The", "2004"));
table.insert(new Film("Robots", "2005"));
table.insert(new Film("SpongeBob SquarePants Movie, The", "2004"));
table.insert(new Film("Son of the Mask", "2005"));
table.insert(new Film("Constantine", "2005"));
table.insert(new Film("Beyond the Sea", "2004"));
table.insert(new Film("Million Dollar Baby", "2004"));
table.insert(new Film("As Good As It Gets", "1997"));
table.insert(new Film("Wedding Date, The", "2005"));
table.insert(new Film("Doll Master", "2005"));
table.insert(new Film("Kinsey", "2004"));
table.insert(new Film("Fetten Jahre sind vorbei, Die / Edukators, The", "2004"));
table.insert(new Film("Genesis", "2004"));
table.insert(new Film("Racing Stripes", "2005"));
table.insert(new Film("Hercules", "1997"));
table.insert(new Film("Filme de Amor", "2003"));
table.insert(new Film("Boogeyman", "2005"));
table.insert(new Film("From 180 and Higher", "2004"));
table.insert(new Film("Dinosaur", "2000"));
table.insert(new Film("Toy Story 2", "1999"));
table.insert(new Film("Be Cool", "2005"));
table.insert(new Film("Ring Two, The", "2005"));
table.insert(new Film("Sin City", "2005"));
table.insert(new Film("Woodsman, The", "2004"));
table.insert(new Film("Eros", "2004"));
table.insert(new Film("9 Songs", "2004"));
table.insert(new Film("Star Wars: Episode III - Revenge of the Sith", "2005"));
table.insert(new Film("Miss Congeniality 2: Armed and Fabulous", "2005"));
table.insert(new Film("Sahara", "2005"));
table.insert(new Film("Pacifier, The", "2005"));
table.insert(new Film("Weather Man", "2005"));
table.insert(new Film("XXX: State of the Union", "2005"));
table.insert(new Film("She Hate Me", "2004"));
table.insert(new Film("Clefs de bagnole, Les", "2003"));
table.insert(new Film("One Flew Over the Cockoo`s Nest", "1975"));
table.insert(new Film("Last Tango in Paris", "1972 "));
table.insert(new Film("Japanese Story", "2003"));
table.insert(new Film("The Beatles: Yellow Submarine", "1968 "));
table.insert(new Film("Par - del? les nuages", "1995"));
table.insert(new Film("Heaven and Hell / Tengoku to-jigoku", "1963"));
table.insert(new Film("Back to Gaya", "2004"));
table.insert(new Film("36 Quai des Orfevres", "2004"));
table.insert(new Film("Alone in the Dark", "2005"));
table.insert(new Film("Valiant", "2005"));
table.insert(new Film("Kingdom of Heaven", "2005"));
table.insert(new Film("Diarios de motocicleta / Motorcycle Diaries, The", "2004"));
table.insert(new Film("Exorcist: The Beginning", "2004"));
table.insert(new Film("One Missed Call 2", "2005"));
table.insert(new Film("Mulan", "1998"));
table.insert(new Film("Charlie and the Chocolate Factory", "2005"));
table.insert(new Film("Shallow Ground", "2004"));
table.insert(new Film("Chungking Express / Chung Hing sam lam", "1994"));
table.insert(new Film("Zabriskie ?oint", "1970"));
table.insert(new Film("Night Porter, The", "1974"));
table.insert(new Film("Breaking the waves", "1996"));
table.insert(new Film("Interpreter, The", "2005"));
table.insert(new Film("Cielo abierto, El", "2001"));
table.insert(new Film("Mar adentro / Sea Inside, The", "2004"));
table.insert(new Film("Lot Like Love, A", "2005"));
table.insert(new Film("Amityville Horror, The", "2005"));
table.insert(new Film("Zhmurki", "2005"));
table.insert(new Film("Les Amants Criminels", "1999"));
table.insert(new Film("Pillow Book, The", "1996"));
table.insert(new Film("Elephant Man,The", "1980"));
table.insert(new Film("I Hired a Contract Killer", "1990"));
table.insert(new Film("Tokyo Story", "1953"));
table.insert(new Film("A Zed and Two Noughts", "1985"));
table.insert(new Film("When Father Was Away On Business", "1985"));
table.insert(new Film("Man-Thing", "2005"));
table.insert(new Film("Vremya sobirat kamni", "2005"));
table.insert(new Film("Return to Sender", "2004"));
table.insert(new Film("Dalton, Les", "2004"));
table.insert(new Film("Jacket, The", "2005"));
table.insert(new Film("Silent Partner", "2005"));
table.insert(new Film("Madagascar", "2005"));
table.insert(new Film("Inside Deep Throat", "2005"));
table.insert(new Film("Five Obstructions, The", "2003"));
table.insert(new Film("Reservoir Dogs", "1992"));
table.insert(new Film("Les Cotelettes", "2003"));
table.insert(new Film("Wings of Desire ", "1988"));
table.insert(new Film("Mein Bruder ist ein Hund", "2004"));
table.insert(new Film("Mighty Joe Young", "1998"));
table.insert(new Film("Mr. and Mrs. Smith", "2005"));
table.insert(new Film("Batman Begins", "2005"));
table.insert(new Film("Living Forest, The", "2001"));
table.insert(new Film("Guess Who", "2005"));
table.insert(new Film("War Of The Worlds", "2005"));
table.insert(new Film("Fantastic Four", "2005"));
table.insert(new Film("Monster-in-Law", "2005"));
table.insert(new Film("C(r)ook, The", "2004"));
table.insert(new Film("Napola", "2004"));
table.insert(new Film("Assassination of Richard Nixon, The", "2004"));
table.insert(new Film("Boudu", "2005"));
table.insert(new Film("Sisterhood of the Traveling Pants, The", "2005"));
table.insert(new Film("Kung Fu Hustle", "2004"));
table.insert(new Film("Brothers Grimm, The", "2005"));
table.insert(new Film("Island, The", "2005"));
table.insert(new Film("Colour Me Kubrick", "2005"));
table.insert(new Film("Bridge of San Luis Rey, The", "2004"));
table.insert(new Film("Carton, Le", "2004"));
table.insert(new Film("Anthony Zimmer", "2005"));
table.insert(new Film("Sitcom", "1998"));
table.insert(new Film("Rumble Fish", "1983"));
table.insert(new Film("Land of Plenty", "2004"));
table.insert(new Film("Koyaanisqatsi", "1983"));
table.insert(new Film("Iznogoud", "2005"));
table.insert(new Film("Manderlay", "2005"));
table.insert(new Film("Inconscientes", "2004"));
table.insert(new Film("Longest Yard, The", "2005"));
table.insert(new Film("Tony Takitani", "2004"));
table.insert(new Film("Poupees russes, Les", "2005"));
table.insert(new Film("Choristes, Les", "2004"));
table.insert(new Film("Mysterious Skin", "2004"));
table.insert(new Film("Dear Wendy", "2005"));
table.insert(new Film("Bipedalism", "2004"));
table.insert(new Film("Abrafaxe - Unter schwarzer Flagge, Die", "2001"));
table.insert(new Film("Stealth", "2005"));
table.insert(new Film("Tian bian yi duo yun", "2005"));
table.insert(new Film("Blood and Bones / Chi to hone", "2004"));
table.insert(new Film("Tie me up! Tie me down!", "1990"));
table.insert(new Film("Woman in the Dunes / Suna no onna", "1964"));
table.insert(new Film("Eraserhead", "1977"));
table.insert(new Film("Arizona Dream", "1993"));
table.insert(new Film("Blowup", "1966"));
table.insert(new Film("Dead Man", "1995"));
table.insert(new Film("Ed Wood", "1994"));
table.insert(new Film("Breathless", "1960"));
table.insert(new Film("Les Valseuses", "1974"));
table.insert(new Film("Liquid Sky", "1982"));
table.insert(new Film("Csontvary", "1980"));
table.insert(new Film("Mystery Train", "1989"));
table.insert(new Film("In The Realms Of Senses", "1976"));
table.insert(new Film("Draughtsman`s Contract, The ", "1982"));
table.insert(new Film("The Last Temptation of Christ", "1988"));
table.insert(new Film("Easy Rider", "1969"));
table.insert(new Film("The Piano", "1993"));
table.insert(new Film("Tacones lejanos", "1991"));
table.insert(new Film("Requiem for a Dream", "2000"));
table.insert(new Film("Twin Peaks: Fire Walk With Me", "1992"));
table.insert(new Film("Living In Oblivion", "1995"));
table.insert(new Film("Night on Earth", "1991"));
table.insert(new Film("Unbearable Lightness of Being, The", "1988"));
table.insert(new Film("Pierrot le Fou", "1965"));
table.insert(new Film("Zentropa / Europa", "1991"));
table.insert(new Film("Untergang, Der", "2004"));
table.insert(new Film("House of Wax", "2005"));
table.insert(new Film("Luz prodigiosa, La", "2003"));
table.insert(new Film("Adventures of SharkBoy and LavaGirl in 3-D, The", "2005"));
table.insert(new Film("Herbie Fully Loaded", "2005"));
table.insert(new Film("Skeleton Key, The", "2005"));
table.insert(new Film("Aeon Flux", "2005"));
table.insert(new Film("Land of the Dead", "2005"));
table.insert(new Film("Going the Distance", "2004"));
table.insert(new Film("Ze film", "2005"));
table.insert(new Film("Bewitched", "2005"));
table.insert(new Film("Barfuss", "2005"));
table.insert(new Film("Total Eclipse", "1995"));
table.insert(new Film("If?", "1968"));
table.insert(new Film("Samurai assassin", "1965"));
table.insert(new Film("Permanent Vacation", "1980"));
table.insert(new Film("The Cook, The Thief, His Wife & Her Lover", "1989"));
table.insert(new Film("In The Mood For Love", "2000"));
table.insert(new Film("Plus beau jour de ma vie, Le", "2004"));
table.insert(new Film("Red-Eye", "2005"));
table.insert(new Film("Salome`s Last Dance", "1988"));
table.insert(new Film("Death in Venice", "1971"));
table.insert(new Film("Batalla en el cielo / Battle in Heaven", "2005"));
table.insert(new Film("My Summer of Love", "2004"));
table.insert(new Film("Grande bouffe, La", "1973"));
table.insert(new Film("The Big Lebowski", "1998"));
table.insert(new Film("Caravaggio", "1986"));
table.insert(new Film("Ten Minutes Older: Trumpet", "2002"));
table.insert(new Film("Deuce Bigalow: European Gigolo", "2005"));
table.insert(new Film("Wedding Crashers, The", "2005"));
table.insert(new Film("Brice de Nice", "2005"));
table.insert(new Film("Besieged", "1998"));
table.insert(new Film("Fear and Loathing in Las Vegas", "1998"));
table.insert(new Film("Water Drops on Burning Rocks", "2000"));
table.insert(new Film("Dodes`ka-den", "1970"));
table.insert(new Film("Mishima", "1985"));
table.insert(new Film("Four", "2004"));
table.insert(new Film("Kiss, The / De Kus", "2004"));
table.insert(new Film("Deuce Bigalow: Male Gigolo", "1999"));
table.insert(new Film("Cinderella Man", "2005"));
table.insert(new Film("Transporter 2, The", "2005"));
table.insert(new Film("Great Raid, The", "2005"));
table.insert(new Film("Fa dou daai jin", "2004"));
table.insert(new Film("Madchen, Madchen 2 - Loft oder Liebe", "2004"));
table.insert(new Film("Crash", "2004"));
table.insert(new Film("Three... Extremes / Saam gaang yi", "2004"));
table.insert(new Film("School for seduction", "2004"));
table.insert(new Film("Revolver", "2005"));
table.insert(new Film("When Will I Be Loved", "2004"));
table.insert(new Film("Antikorper", "2005"));
table.insert(new Film("Underclassman, The", "2005"));
table.insert(new Film("Sky High", "2005"));
table.insert(new Film("40 Year-Old Virgin, The", "2005"));
table.insert(new Film("Happy Endings", "2005"));
table.insert(new Film("Four Brothers", "2005"));
table.insert(new Film("Constant Gardener, The", "2005"));
table.insert(new Film("Dark Water", "2005"));
table.insert(new Film("Serenity", "2005"));
table.insert(new Film("Broken Flowers", "2005"));
table.insert(new Film("Oliver Twist", "2005"));
table.insert(new Film("Legend of Zorro, The", "2005"));
table.insert(new Film("Wallace & Gromit Movie: Curse of the Were-Rabbit, The", "2005"));
table.insert(new Film("Doom", "2005"));
table.insert(new Film("Elizabethtown", "2005"));
table.insert(new Film("Corpse Bride", "2005"));
table.insert(new Film("King Kong", "2005"));
table.insert(new Film("Harry Potter and the Goblet of Fire", "2005"));
table.insert(new Film("Hwal", "2005"));
table.insert(new Film("Time to Leave / Temps qui reste, Le", "2005"));
table.insert(new Film("Pride and Prejudice", "2005"));
table.insert(new Film("Exorcism of Emily Rose, The", "2005"));
table.insert(new Film("V for Vendetta", "2005"));
table.insert(new Film("Dukes of Hazzard, The", "2005"));
table.insert(new Film("Chicken Little", "2005"));
table.insert(new Film("Into the Blue", "2005"));
table.insert(new Film("Unfinished Life, An", "2005"));
table.insert(new Film("Forty Shades of Blue", "2005"));
table.insert(new Film("Edison", "2005"));
table.insert(new Film("Havoc", "2005"));
table.insert(new Film("Two for the Money", "2005"));
table.insert(new Film("Midsummer Dream", "2005"));
table.insert(new Film("Domino", "2005"));
table.insert(new Film("Tickets", "2005"));
table.insert(new Film("Last Days", "2005"));
table.insert(new Film("Garpastum", "2005"));
table.insert(new Film("One Day in Europe", "2005"));
table.insert(new Film("Blue Velvet", "1986"));
table.insert(new Film("Flightplan", "2005"));
table.insert(new Film("Goal!", "2005"));
table.insert(new Film("Fog, The", "2005"));
table.insert(new Film("History of Violence, A", "2005"));
table.insert(new Film("Dungeons & Dragons: Wrath of the Dragon God", "2005"));
table.insert(new Film("Just Like Heaven", "2005"));
table.insert(new Film("Must Love Dogs", "2005"));
table.insert(new Film("Chronicles of Narnia: The Lion, the Witch and the Wardrobe, The", "2005"));
table.insert(new Film("Supercross", "2005"));
table.insert(new Film("In Her Shoes", "2005"));
table.insert(new Film("Prime", "2005"));
table.insert(new Film("Sound of Thunder, A", "2005"));
table.insert(new Film("Shopgirl", "2005"));
table.insert(new Film("Proof", "2005"));
table.insert(new Film("Palindromes", "2004"));
table.insert(new Film("(T)Raumschiff Surprise - Periode 1", "2004"));
table.insert(new Film("Hole In My Heart, A", "2004"));
table.insert(new Film("Italian,The", "2005"));
table.insert(new Film("Lord of War", "2005"));
table.insert(new Film("Zathura: A Space Adventure", "2005"));
table.insert(new Film("Casanova", "2005"));
table.insert(new Film("Day Watch", "2005"));
table.insert(new Film("Antidote, L", "2005"));
table.insert(new Film("Family Stone, The", "2005"));
table.insert(new Film("Munich", "2005"));
table.insert(new Film("Saw II", "2005"));
table.insert(new Film("Long Weekend, The", "2005"));
table.insert(new Film("Nouvelle-France", "2004"));
table.insert(new Film("Descent, The", "2005"));
table.insert(new Film("Cry_Wolf", "2005"));
table.insert(new Film("Piccadilly Jim", "2004"));
table.insert(new Film("Parrains, Les", "2005"));
table.insert(new Film("Gaous, Les", "2004"));
table.insert(new Film("Waiting...", "2005"));
table.insert(new Film("Kaptein Sabeltann", "2003"));
table.insert(new Film("Tamara", "2005"));
table.insert(new Film("JABBERWOCKY", "1977"));
table.insert(new Film("Phenomena", "1985"));
table.insert(new Film("Hollywood Ending", "2002"));
table.insert(new Film("Hoodwinked", "2005"));
table.insert(new Film("Bottoms up! / A boire", "2004"));
table.insert(new Film("Guidebook, The", "2004"));
table.insert(new Film("Oscar And Josefine", "2005"));
table.insert(new Film("Where the Truth Lies", "2005"));
table.insert(new Film("Jarhead", "2005"));
table.insert(new Film("Ice Harvest", "2005"));
table.insert(new Film("Chevaliers du ciel, Les", "2005"));
table.insert(new Film("Derailed", "2005"));
table.insert(new Film("Memoirs of a Geisha", "2005"));
table.insert(new Film("Bandidas", "2006"));
table.insert(new Film("Cheaper by the Dozen 2", "2005"));
table.insert(new Film("Bal-Can-Can", "2005"));
table.insert(new Film("Joyeux Noel", "2005"));
table.insert(new Film("Kiss Kiss Bang Bang", "2005"));
table.insert(new Film("Libertine, The", "2004"));
table.insert(new Film("Mongolian Ping Pong / Lu cao di", "2005"));
table.insert(new Film("Initial D / Tau man ji D", "2005"));
table.insert(new Film("Rumor Has It...", "2005"));
table.insert(new Film("Underworld: Evolution", "2006"));
table.insert(new Film("Just Friends", "2005"));
table.insert(new Film("Walk the Line", "2005"));
table.insert(new Film("Nowhere", "1997"));
table.insert(new Film("Buffet froid", "1979"));
table.insert(new Film("Totally F***ed Up", "1993"));
table.insert(new Film("F For Fake", "1974"));
table.insert(new Film("Ice Age 2: The Meltdown", "2006"));
table.insert(new Film("Mission: Impossible III", "2006"));
table.insert(new Film("Da Vinci Code, The", "2006"));
table.insert(new Film("Pink Panther, The", "2005"));
table.insert(new Film("Aziris Nuna", "2006"));
table.insert(new Film("Stay", "2005"));
table.insert(new Film("Fun with Dick and Jane", "2005"));
table.insert(new Film("Basic Instinct 2: Risk Addiction", "2006"));
table.insert(new Film("BloodRayne", "2005"));
table.insert(new Film("Heart Is Deceitful Above All Things, The", "2004"));
table.insert(new Film("Match Point", "2005"));
table.insert(new Film("Down in the Valley", "2005"));
table.insert(new Film("Big White, The", "2005"));
table.insert(new Film("Syriana", "2005"));
table.insert(new Film("Ultraviolet", "2006"));
table.insert(new Film("Matador, The", "2005"));
table.insert(new Film("Date Movie", "2006"));
table.insert(new Film("Chumscrubber, The", "2005"));
table.insert(new Film("Hostel", "2005"));
table.insert(new Film("Life Aquatic with Steve Zissou, The", "2004"));
table.insert(new Film("Alibi, The", "2005"));
table.insert(new Film("Kakushi-ken: oni no tsume", "2004"));
table.insert(new Film("Brokeback Mountain", "2005"));
table.insert(new Film("Hustle & Flow", "2005"));
table.insert(new Film("Tristan & Isolde", "2006"));
table.insert(new Film("Wolf Creek", "2005"));
table.insert(new Film("Myth, The / San wa", "2005"));
table.insert(new Film("16 Blocks", "2006"));
table.insert(new Film("Un fil ? la patte", "2005"));
table.insert(new Film("Dark, The", "2005"));
table.insert(new Film("Failure to Launch", "2006"));
table.insert(new Film("Angel A", "2005"));
table.insert(new Film("Night, and Good Luck", "2005"));
table.insert(new Film("Running Scared", "2006"));
table.insert(new Film("Nanny McPhee", "2005"));
table.insert(new Film("Final Destination 3", "2006"));
table.insert(new Film("Tigre e la neve, La", "2005"));
table.insert(new Film("Polizistin, Die", "2000"));
table.insert(new Film("Bin ich schoen?", "1998"));
table.insert(new Film("Day Without a Mexican, A", "2004"));
table.insert(new Film("Yours, Mine and Ours", "2005"));
table.insert(new Film("Firewall", "2006"));
table.insert(new Film("Scary Movie 4", "2006"));
table.insert(new Film("Inside Man", "2006"));
table.insert(new Film("Wild, The", "2006"));
table.insert(new Film("Keeping Mum", "2005"));
table.insert(new Film("Bibi Blocksberg und das Geheimnis der blauen Eulen", "2004"));
table.insert(new Film("Viy", "2009"));
table.insert(new Film("X-Men: The Last Stand", "2006"));
table.insert(new Film("Cars", "2006"));
table.insert(new Film("Over the Hedge", "2006"));
table.insert(new Film("Omen, The", "2006"));
table.insert(new Film("Hills Have Eyes, The", "2006"));
table.insert(new Film("Superman Returns", "2006"));
table.insert(new Film("Lust och fagring stor", "1995"));
table.insert(new Film("De battre mon coeur s est arrete", "2005"));
table.insert(new Film("Best Man, The", "2005"));
table.insert(new Film("Lucky Number Slevin", "2006"));
table.insert(new Film("Mary", "2005"));
table.insert(new Film("Shaggy Dog, The", "2006"));
table.insert(new Film("Poseidon", "2006"));
table.insert(new Film("Silent Hill", "2006"));
table.insert(new Film("Ask the Dust", "2006"));
table.insert(new Film("Parent Trap, The", "1998"));
table.insert(new Film("Alpha Dog", "2006"));
table.insert(new Film("United 93", "2006"));
table.insert(new Film("Promise, The / Wu ji", "2005"));
table.insert(new Film("Fast and the Furious: Tokyo Drift, The", "2006"));
table.insert(new Film("Wolfhound,The", "2006"));
table.insert(new Film("Dead Daughters", "2006"));
table.insert(new Film("Proposition, The", "2005"));
table.insert(new Film("Romance & Cigarettes", "2005"));
table.insert(new Film("Mrs. Henderson Presents", "2005"));
table.insert(new Film("U-Carmen e-Khayelitsha", "2005"));
table.insert(new Film("Stay Alive", "2006"));
table.insert(new Film("Amores Perros", "2000"));
table.insert(new Film("Kika", "1993"));
table.insert(new Film("Viva Cuba", "2005"));
table.insert(new Film("Breakfast on Pluto", "2005"));
table.insert(new Film("Factotum", "2005"));
table.insert(new Film("When a Stranger Calls", "2006"));
table.insert(new Film("Sheitan", "2006"));
table.insert(new Film("Das Wunder von Bern", "2003"));
table.insert(new Film("Lassie", "2005"));
table.insert(new Film("Tideland", "2005"));
table.insert(new Film("Minotaur", "2005"));
table.insert(new Film("Manner wie wir", "2004"));
table.insert(new Film("Producers, The", "2005"));
table.insert(new Film("Mee-Shee: The Water Giant", "2005"));
table.insert(new Film("Just My Luck", "2006"));
table.insert(new Film("Volver", "2006"));
table.insert(new Film("She is the Man", "2006"));
table.insert(new Film("Lemming", "2005"));
table.insert(new Film("Chaos", "2005"));
table.insert(new Film("Lovewrecked", "2005"));
table.insert(new Film("Break-Up, The", "2006"));
table.insert(new Film("See No Evil", "2006"));
table.insert(new Film("R.V.", "2006"));
table.insert(new Film("Slither", "2006"));
table.insert(new Film("Cactus, Le", "2005"));
table.insert(new Film("American Dreamz", "2006"));
table.insert(new Film("Garfield: A Tail of Two Kitties", "2006"));
table.insert(new Film("Candy", "2006"));
table.insert(new Film("Devil Wears Prada", "2006"));
table.insert(new Film("Bob the Butler", "2005"));
table.insert(new Film("Pribehy obycejneho silenstvi", "2005"));
table.insert(new Film("El Topo", "1970"));
table.insert(new Film("Farewell, Home Sweet Home", "1999"));
table.insert(new Film("Magnolia", "1999"));
table.insert(new Film("Ley del deseo, La", "1987"));
table.insert(new Film("Down by law", "1986"));
table.insert(new Film("2001 Maniacs", "2005"));
table.insert(new Film("Pledge This!", "2006"));
table.insert(new Film("Cidade Baixa", "2005"));
table.insert(new Film("Il ne faut jurer... de rien!", "2005"));
table.insert(new Film("Stick It", "2006"));
table.insert(new Film("Doublure, La", "2000"));
table.insert(new Film("Deep Sea 3D", "2006"));
table.insert(new Film("Magnificent Desolation: Walking on the Moon 3D", "2006"));
table.insert(new Film("Adventures in Animation 3D", "2004"));
table.insert(new Film("Galapagos: The Enchanted Voyage ", "1999"));
table.insert(new Film("Wild Safari 3D", "2005"));
table.insert(new Film("Aliens of the Deep 3D", "2005"));
table.insert(new Film("Sharks 3D", "2004"));
table.insert(new Film("Haunted Castle", "2001"));
table.insert(new Film("Misadventures in 3D", "2003"));
table.insert(new Film("Bugs! 3D", "2003"));
table.insert(new Film("T-Rex: Back to the Cretaceous", "1998"));
table.insert(new Film("American Haunting, An", "2005"));
table.insert(new Film("Click", "2006"));
table.insert(new Film("Miami Vice", "2006"));
table.insert(new Film("Lake House, The", "2006"));
table.insert(new Film("Lady in the Water", "2006"));
table.insert(new Film("My Super Ex-Girlfriend", "2006"));
table.insert(new Film("Man About Town", "2006"));
table.insert(new Film("Pulse", "2006"));
table.insert(new Film("Perfume: The Story of a Murderer", "2006"));
table.insert(new Film("Honey Baby", "2003"));
table.insert(new Film("Vinho de Rosas", "2005"));
table.insert(new Film("Rozdroze Cafe", "2005"));
table.insert(new Film("Mistress of Spices", "2005"));
table.insert(new Film("Three Burials of Melquiades Estrada, The", "2005"));
table.insert(new Film("Enfer, L`", "2005"));
table.insert(new Film("Nyocker! / The Disrict", "2004"));
table.insert(new Film("13 (Tzameti)", "2005"));
table.insert(new Film("Ocean Wonderland 3D", "2006"));
table.insert(new Film("Driving Lessons", "2006"));
table.insert(new Film("Stealing Beauty / Io ballo da sola ", "1996"));
table.insert(new Film("Underground", "1995"));
table.insert(new Film("Contempt / Disprezzo, Il", "1963"));
table.insert(new Film("Marerial girls", "2006"));
table.insert(new Film("Spider-Man 3", "2007"));
table.insert(new Film("American Graffiti", "1973"));
table.insert(new Film("Powaqqatsi", "1988"));
table.insert(new Film("Juha", "1999"));
table.insert(new Film("Zodiac, The", "2005"));
table.insert(new Film("Sentinel, The", "2006"));
table.insert(new Film("You, Me and Dupree", "2006"));
table.insert(new Film("Nomad", "2005"));
table.insert(new Film("Prairie Home Companion, A", "2006"));
table.insert(new Film("Superman Returns", "2006"));
table.insert(new Film("Shadows in Paradise", "1986"));
table.insert(new Film("I Will Walk Like a Crazy Horse", "1973"));
table.insert(new Film("Takeshis`", "2005"));
table.insert(new Film("Casino Royale", "2006"));
table.insert(new Film("Fakiren fra Bilbao", "2004"));
table.insert(new Film("Curious George", "2006"));
table.insert(new Film("Monster House", "2006"));
table.insert(new Film("Stormbreaker", "2006"));
table.insert(new Film("Clerks 2", "2006"));
table.insert(new Film("Snakes on a Plane", "2006"));
table.insert(new Film("Asterix et les Vikings", "2006"));
table.insert(new Film("Shinobi: Heart under Blade", "2005"));
table.insert(new Film("Crank", "2006"));
table.insert(new Film("Saat po long", "2006"));
table.insert(new Film("Citizen Kane", "1941"));
table.insert(new Film("Adventures of Picasso, The", "1978"));
table.insert(new Film("Appurushido / Appleseed", "2004"));
table.insert(new Film("Casablanca", "1942"));
table.insert(new Film("Falling Leaves", "1966"));
table.insert(new Film("Je T`aime, Je T`aime", "1968"));
table.insert(new Film("Henry and June", "1990"));
table.insert(new Film("Eyes Wide Shut", "1999"));
table.insert(new Film("A Man And A Woman", "1966"));
table.insert(new Film("The Grim Reaper / La Commare secca", "1962"));
table.insert(new Film("Hanussen", "1988"));
table.insert(new Film("Tango", "1992"));
table.insert(new Film("Edward II", "1991"));
table.insert(new Film("Man bites dog", "1992"));
table.insert(new Film("Wild Strawberries / Smultronstallet", "1957"));
table.insert(new Film("Paris, Texas", "1984"));
table.insert(new Film("Professione: reporter / The passenger", "1975"));
table.insert(new Film("American Beauty", "1999"));
table.insert(new Film("All the Invisible Children", "2005"));
table.insert(new Film("Take the Lead", "2006"));
table.insert(new Film("Accepted", "2006"));
table.insert(new Film("Nacho Libre", "2006"));
table.insert(new Film("Vida secreta de las palabras, La", "2005"));
table.insert(new Film("Fearless", "2006"));
table.insert(new Film("Everyone`s Hero", "2006"));
table.insert(new Film("Black Dahlia, The", "2006"));
table.insert(new Film("Wicker Man, The", "2006"));
table.insert(new Film("Trust The Man", "2005"));
table.insert(new Film("Atomised/Elementarteilchen", "2006"));
table.insert(new Film("World Trade Center", "2006"));
table.insert(new Film("Nankin Landscape", "2006"));
table.insert(new Film("Euphoria", "2006"));
table.insert(new Film("Guardian, The", "2006"));
table.insert(new Film("Children of Men, The", "2006"));
table.insert(new Film("Pirates of the Caribbean: At worlds end", "2007"));
table.insert(new Film("Killshot", "2009"));
table.insert(new Film("DOA: Dead or Alive", "2006"));
table.insert(new Film("Sympathy for Mr. Vengeance/ Boksuneun naui geot ", "2002"));
table.insert(new Film("Sympathy for Lady Vengeance/ Chinjeol-han Geumja-ssi", "2005"));
table.insert(new Film("Wind That Shakes the Barley, The", "2006"));
table.insert(new Film("Flushed Away", "2006"));
table.insert(new Film("Bluthochzeit, Die", "2005"));
table.insert(new Film("En Soap", "2006"));
table.insert(new Film("Twelve Monkeys", "1995"));
table.insert(new Film("Flight of the Navigator", "1986"));
table.insert(new Film("Bitter Moon", "1992"));
table.insert(new Film("The Sheltering Sky", "1990"));
table.insert(new Film("Pretty Baby", "1978"));
	}
}